### ISSUE TITLE
With consul, docker-compose, how to check all the rabbitmq nodes get clustered properly?

### ISSUE THREAD

**Issue by ldshi** [aweber/rabbitmq-autocluster#100]
Thanks for this great job.

I am able to set this up with consul, docker-compose, and all the nodes/services got registered properly, and also no any errors in each node's log, but how can I know all the nodes already got clustered properly?

I tried /bin/bash into docker container and check with the 'rabbitmqctl cluster_status', but got the following error:

```
leonard@docker01:~/microservice-rabbitmq$ docker run -it microservicerabbitmq_rabbitmq-server-0 /bin/bash
root@37d5a5b07b87:/# rabbitmqctl cluster_status
Cluster status of node rabbit@37d5a5b07b87 ...
Error: unable to connect to node rabbit@37d5a5b07b87: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@37d5a5b07b87]

rabbit@37d5a5b07b87:
  * connected to epmd (port 4369) on 37d5a5b07b87
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on 37d5a5b07b87
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-88@37d5a5b07b87'
- home dir: /var/lib/rabbitmq
- cookie hash: SRsDkpOcVius8R4rjFLr1g==

root@37d5a5b07b87:/#
```

And also I set the UI management plugin up, then checked in the **_overview -> node_** section, but only can see one node.

So how should I check?

**Comment by binarin** [comment]
You should use ` docker exec` instead, because `run` starts a new container.

**Comment by leonard-sxy** [comment]
@binarin no.
@gmr I confirmed this, seems totally cannot work with docker + consul. I managed to construct the cluster manually in docker + consul environment, everything works fine now.

Use this plugin to auto register services to consul + manually construct the rabbit cluster is also not bad.

And I think if I get time will think how to contribute the docker + consul environment rabbit cluster construction part.

**Comment by binarin** [comment]
@leonard-sxy Yes =) By doing `docker run ... /bin/bash`  you are starting a fresh container, where nothing except bash is running - so there is nothing surprising in the fact that `cluster_status`  reports an error. Or if you want to perform check from a separate container, you have to provide `-n` argument for `rabbitmqctl`with some resolvable node name.

You didn't provide any details, but I think that `resolvable` is your actual problem. Because everything works fine when IP-addresses are used for clustering inside docker.

**Comment by leonard-sxy** [comment]
@binarin thanks, stop commenting, seems u a not in quite right direction..., nothing to do with `docker run`
```
docker run -it --rm \
--network=consul-cluster \
--link rabbitmq-server-1 \
-e "RABBITMQ_ERLANG_COOKIE=COOKIE_VAL_HERE" \
-e "RABBITMQ_NODENAME=rabbit@rabbitmq-server-1" \
rabbitmq:3.6.5-management bash
```

**Comment by Gsantomaggio** [comment]
hi @ldshi 

Check this [example](https://github.com/Gsantomaggio/rabbitmqexample/tree/master/cluster_docker_compose/consul
) 
You can create a cluster using `consul` with `docker-compose` I had to add a [`startup-delay` ](https://github.com/Gsantomaggio/rabbitmqexample/blob/master/cluster_docker_compose/consul/conf/rabbitmq.config#L6)

The example enables the management UI, so you can check the status on the UI (http://ip:15673/#/ or http://ip:15672/#/ )

I used an high startup delay, so you could wait ~40 seconds before see the cluster 

as @binarin said to check the cluster status you can also use `docker exec ` is this way: 
```
sudo docker exec -i -t  consul_rabbit_node_1_1 /bin/bash -c "rabbitmqctl cluster_status"
Cluster status of node rabbit@rabbit_node_1 ...
[{nodes,[{disc,[rabbit@rabbit_node_1,rabbit@rabbit_node_2]}]},
 {running_nodes,[rabbit@rabbit_node_2,rabbit@rabbit_node_1]},
 {cluster_name,<<"rabbit@rabbit_node_2">>},
 {partitions,[]},
 {alarms,[{rabbit@rabbit_node_2,[]},{rabbit@rabbit_node_1,[]}]}]
```
