### ISSUE TITLE
wiki is globally editable?

### ISSUE THREAD

**Issue by oli-logicnow** [aweber/rabbitmq-autocluster#101]
Hi,
It might be by choice, but your wiki pages are globally editable.  Only noticed after I made a bad edit.  https://github.com/aweber/rabbitmq-autocluster/wiki/AWS-Configuration/_history

Maybe switch to contributors only?

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
