### ISSUE TITLE
k8s image

### ISSUE THREAD

**Issue by FrederikNS** [aweber/rabbitmq-autocluster#103]
Hi

I'm trying to setup a RabbitMQ cluster in Kubernetes. It seems that all the code is in place, but I would love to not have to build my own. The image you provide unfortunately does not include the Kubernetes changes, and neither does the release. Is there any chance that I could get a docker image with Kubernetes support? I would be very grateful!

Best Regards

Frederik

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
