### ISSUE TITLE
Wiki contains outdated information about logging configuration

### ISSUE THREAD

**Issue by binarin** [aweber/rabbitmq-autocluster#106]
Doing it as described at 
https://github.com/aweber/rabbitmq-autocluster/wiki/General%20Settings#logging-configuration
no longer works, as https://github.com/aweber/rabbitmq-autocluster/blob/9ed821379c370ca1ce8e4a2dd55501fcf76d4e65/src/autocluster.erl#L402 updates `rabbit/log_levels` unconditionally. 

If you don't mind, I'll delete this chunk from wiki myself.

**Comment by gmr** [comment]
That's why it's open for anyone to edit :) GFI
