### ISSUE TITLE
Checksum for releases?

### ISSUE THREAD

**Issue by careys7** [aweber/rabbitmq-autocluster#107]
I'm running automated builds of Docker images using autocluster plugin - is there somewhere that I can retrieve a checksum for the `tgz` files on the [releases](https://github.com/aweber/rabbitmq-autocluster/releases) page?

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
