### ISSUE TITLE
RabbitMQ AutoCluster using Consul is not working

### ISSUE THREAD

**Issue by vyomtandon** [aweber/rabbitmq-autocluster#110]
First of all, I would appreciate for creating such a awesome utility, I ran into below errors while following the steps mentioned below, Kindly share the details in case I am missing anything.
 
## Error Message
While starting the second & third RabbitMQ instances the below error is seen and the nodes is not able to join the Cluster
```
=ERROR REPORT==== 11-Nov-2016::00:20:00 ===
autocluster: Can not communicate with cluster nodes.
```

## Steps to Reproduce :
I ran the below commands as per the steps mentioned below and happen to recive the error `autocluster: Can not communicate with cluster nodes.`
```
docker build -t gavinmroy/autocluster .

docker run --rm -t -i --name=consul -p 8500:8500 gavinmroy/alpine-consul:0.5.2-0

docker run --rm -t -i --link=consul --name=node0 -e AUTOCLUSTER_TYPE=consul -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e CONSUL_SERVICE_TTL=60 -e CONSUL_AUTO_ADDRESS=true -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -p 15672:15672 gavinmroy/autocluster

docker run --rm -t -i --link=consul --link=node0 --name=node1 -e RABBITMQ_NODE_TYPE=ram -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e AUTOCLUSTER_TYPE=consul -e CONSUL_AUTO_ADDRESS=true -e AUTOCLUSTER_CLEANUP=true gavinmroy/autocluster

docker run --rm -t -i --link=consul --link=node0 --link=node1 --name=node2 -e RABBITMQ_NODE_TYPE=ram -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e AUTOCLUSTER_TYPE=consul -e CONSUL_AUTO_ADDRESS=true -e AUTOCLUSTER_CLEANUP=true gavinmroy/autocluster
```

**Comment by michaelklishin** [comment]
```
autocluster: Can not communicate with cluster nodes
```

means that the plugin tried to discover its peers and the returned set was empty (returned no nodes).

**Comment by vyomtandon** [comment]
I have installed docker locally with the ports exposed appropriately, Steps to reproduce is detailed in the comments. Kindly check the commands in case any parameters are missing. I have referred the below document to check the autocluster.

https://github.com/aweber/rabbitmq-autocluster/wiki/Development-Environment

**Comment by vyomtandon** [comment]
I also tried the other way using [alpine-rabbitmq-autocluster](https://github.com/gmr/alpine-rabbitmq-autocluster) but I am getting the same error.

I am attaching the config details

- rabbitmq.config
```
[
  {
    rabbit,
    [
      {loopback_users, []},
      {cluster_partition_handling, autoheal},
      {delegate_count, 64},
      {fhc_read_buffering, false},
      {fhc_write_buffering, false},
      {heartbeat, 60},
      {queue_index_embed_msgs_below, 0},
      {queue_index_max_journal_entries, 8192},
      {log_levels, [{autocluster, info},
                    {connection, error},
                    {channel, warning},
                    {federation, info},
                    {mirroring, info},
                    {shovel, info}]},
      {vm_memory_high_watermark, 0.8}
    ]
  }
].
```

- consul.sh
```
docker run --rm -t -i --name=consul \
	-p 8500:8500 \
	gavinmroy/alpine-consul:0.5.2-0
```

- startrabbit_1.sh
```
docker run -h 192.168.99.100 --link=consul --name=node1 -d \
--net=host \
-e AUTOCLUSTER_TYPE=consul \
-e CONSUL_SCHEME=http \
-e CONSUL_HOST=192.168.99.100 \
-e CONSUL_PORT=8500 \
-e CONSUL_SVC=rabbitmq \
-e CONSUL_SVC_ADDR=node1 \
-e CONSUL_SVC_TTL=60 \
-e RABBITMQ_USE_LONGNAME=true \
-e RABBITMQ_NODENAME=node1 \
-p 4369:4369 \
-p 5672:5672 \
-p 15672:15672 \
-p 25672:25672 \
tandv001/alpine-rabbitmq-autocluster:1.0
```

- startrabbit_2.sh
```
docker run -h 192.168.99.100 --link=consul --name=node2 -d \
--net=host \
-e AUTOCLUSTER_TYPE=consul \
-e CONSUL_SCHEME=http \
-e CONSUL_HOST=192.168.99.100 \
-e CONSUL_PORT=8500 \
-e CONSUL_SVC=rabbitmq \
-e CONSUL_SVC_ADDR=node2 \
-e CONSUL_SVC_TTL=60 \
-e RABBITMQ_USE_LONGNAME=true \
-e RABBITMQ_NODENAME=node2 \
-p 4370:4369 \
-p 5673:5672 \
-p 15673:15672 \
-p 25673:25672 \
tandv001/alpine-rabbitmq-autocluster:1.0
```

- Error Logs
[node2_logs.txt](https://github.com/aweber/rabbitmq-autocluster/files/585085/node2_logs.txt)

- Consul Service Logs
```
[
{
"Node": "67593aa3ad38",
"Address": "172.17.0.2",
"ServiceID": "rabbitmq:node1",
"ServiceName": "rabbitmq",
"ServiceTags": null,
"ServiceAddress": "node1",
"ServicePort": 5672
},
{
"Node": "67593aa3ad38",
"Address": "172.17.0.2",
"ServiceID": "rabbitmq:node2",
"ServiceName": "rabbitmq",
"ServiceTags": null,
"ServiceAddress": "node2",
"ServicePort": 5672
}
]
```

- Consul Health Check
```
[
{
"Node": {
"Node": "consul",
"Address": "172.17.0.2"
},
"Service": {
"ID": "rabbitmq:node1",
"Service": "rabbitmq",
"Tags": null,
"Address": "node1",
"Port": 5672
},
"Checks": [
{
"Node": "consul",
"CheckID": "service:rabbitmq:node1",
"Name": "Service 'rabbitmq' check",
"Status": "passing",
"Notes": "RabbitMQ Auto-Cluster Plugin TTL Check",
"Output": "",
"ServiceID": "rabbitmq:node1",
"ServiceName": "rabbitmq"
},
{
"Node": "consul",
"CheckID": "serfHealth",
"Name": "Serf Health Status",
"Status": "passing",
"Notes": "",
"Output": "Agent alive and reachable",
"ServiceID": "",
"ServiceName": ""
}
]
},
{
"Node": {
"Node": "consul",
"Address": "172.17.0.2"
},
"Service": {
"ID": "rabbitmq:node2",
"Service": "rabbitmq",
"Tags": null,
"Address": "node2",
"Port": 5672
},
"Checks": [
{
"Node": "consul",
"CheckID": "service:rabbitmq:node2",
"Name": "Service 'rabbitmq' check",
"Status": "critical",
"Notes": "RabbitMQ Auto-Cluster Plugin TTL Check",
"Output": "",
"ServiceID": "rabbitmq:node2",
"ServiceName": "rabbitmq"
},
{
"Node": "consul",
"CheckID": "serfHealth",
"Name": "Serf Health Status",
"Status": "passing",
"Notes": "",
"Output": "Agent alive and reachable",
"ServiceID": "",
"ServiceName": ""
}
]
}
]
```

**Comment by binarin** [comment]
RABBITMQ_USE_LONGNAME=true RABBITMQ_NODENAME=node2

node2 doesn't look like long name, long name is something like
rabbit@node2.with.at-least-one.domain or rabbit@172.17.0.4

And I believe that with the options that you are currently giving to docker
you can make it work only with IP-addresses.

Another thing - can you for e.g. do "ping node1" from node2?

11 нояб. 2016 г. 8:56 ДП пользователь "vyomtandon" <notifications@github.com>
написал:

**Comment by vyomtandon** [comment]
`172.17.0.4` is dynamically generated inside docker so we cannot hard code the same. I am using `RABBITMQ_NODENAME=node1@192.168.99.100 \` & ``RABBITMQ_NODENAME=node2@192.168.99.100 \`` still having the same issue

**Comment by binarin** [comment]
Oh, missed that part - you can't do it that way, Erlang distribution will
just not work through exposing ports on host machine. Only direct
connection between containers.  So you could either set nodename to IP from
some startup script INSIDE your container. Or you could use DNS feature of
docker which should work on non-default networks. Anyway, you should start
with finding a way to do ping between containers; then perform clustering
manually with rabbitmqctl; and only when all of this is working properly
you can start debugging autocluster issues.

**Comment by Gsantomaggio** [comment]
Ok I got where is the problem

In this example: https://github.com/aweber/rabbitmq-autocluster/wiki/Development-Environment#testing-consul-behaviors is used `--link` that is a mono-directional link. 

So this example can work only if the order of `join_cluster` respects the links, ex:

1.  `node1`  can join with `node0` works because:

`node1`
```
/ # cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      node0 d84ef4e1c202
172.17.0.2      69ab4d419d2d
```

2.  `node0`  cannot join with `node1` works because:

`node0`
```
/ # cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.1	d84ef4e1c202
```
and in this case (2) you can have: `Can not communicate with cluster nodes` 

The example should be changed by using a bidirectional links, for ex using a docker network  
as I did [here](https://github.com/Gsantomaggio/rabbitmqexample/blob/master/cluster_docker_compose/consul/docker-compose.yml#L55)

**Comment by Gsantomaggio** [comment]
Here is the script:
```
git clone https://github.com/aweber/rabbitmq-autocluster.git test_consul
cd test_consul
make dist
docker build -t gavinmroy/autocluster .
docker network create rabbitmq_network
docker run --rm -t -i --net=rabbitmq_network --name=consul -p 8500:8500 gavinmroy/alpine-consul:0.5.2-0

docker run --rm -t -i --link=consul --net=rabbitmq_network --name=node0 -e AUTOCLUSTER_TYPE=consul -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e CONSUL_SERVICE_TTL=60  -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -e CONSUL_SVC_ADDR_AUTO=true -p 15672:15672 gavinmroy/autocluster

docker run --rm -t -i --link=node0 --net=rabbitmq_network --name=node1 -e RABBITMQ_NODE_TYPE=ram -e AUTOCLUSTER_TYPE=consul -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e CONSUL_SERVICE_TTL=60  -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -e CONSUL_SVC_ADDR_AUTO=true gavinmroy/autocluster

docker run --rm -t -i --link=node1 --net=rabbitmq_network --name=node2 -e RABBITMQ_NODE_TYPE=ram -e AUTOCLUSTER_TYPE=consul -e CONSUL_HOST=consul -e CONSUL_PORT=8500 -e CONSUL_SERVICE_TTL=60  -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -e CONSUL_SVC_ADDR_AUTO=true gavinmroy/autocluster
```
That's the result:

![screen shot 2017-03-08 at 12 57 55](https://cloud.githubusercontent.com/assets/386987/23707009/e4a65996-0410-11e7-8225-72de3014233f.png)

Another problem is that you are using `CONSUL_AUTO_ADDRESS` it has to be  `CONSUL_SVC_ADDR_AUTO`
The documentation needs to be updated.

I'd update the documentation and I'd close the issue
@michaelklishin WDYT?

**Comment by michaelklishin** [comment]
@Gsantomaggio sounds good.

**Comment by Gsantomaggio** [comment]
@michaelklishin done: https://github.com/aweber/rabbitmq-autocluster/wiki/Development-Environment

btw the [wiki is globally editable](https://github.com/aweber/rabbitmq-autocluster/issues/101).

**Comment by michaelklishin** [comment]
Unfortunately I don't have the permissions to change that.
