### ISSUE TITLE
K8S documentation

### ISSUE THREAD

**Issue by stongo** [aweber/rabbitmq-autocluster#112]
I would love to make this work in k8s. Can some documentation get added for the k8s backend?

**Comment by michaelklishin** [comment]
Feel free to contribute it, this is an open source project primarily maintained by a single person.

**Comment by stongo** [comment]
I would if I wasn't struggling to figure out how to use it :)
Might be an idea to require documentation from contributors when merging
PRs to master

**Comment by michaelklishin** [comment]
Small projects cannot afford to put a lot of requirements on contributors: at best you'd end up having pull requests that are never updated to include the docs.

**Comment by pavel987** [comment]
I wrote some: https://github.com/aweber/rabbitmq-autocluster/wiki/k8s%20Configuration

**Comment by Gsantomaggio** [comment]
We are preparing some example.

[Here](https://github.com/rabbitmq/rabbitmq-autocluster/tree/rabbitmq-autocluster_startup-locking-support/examples/k8s_minikube) you can find a full example about K8s ( using `Minikube` )

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
