### ISSUE TITLE
Etcd Full Example

### ISSUE THREAD

**Issue by stongo** [aweber/rabbitmq-autocluster#113]
It would be great to have an example of how to configure rabbitmq completely to work with etcd ie. node naming convention, DNS and/or /etc/hosts configuration. I'm having a lot of trouble groking how to make it work

**Comment by michaelklishin** [comment]
This plugin does not require any node naming conventions, although usually the name part of full node name is `rabbit` (e.g. `rabbit@eng.megacorp.local`).

Every node needs to be able to resolve hostnames of every other node. This is true for RabbitMQ in general (actually, any Erlang-based system), not this plugin. However you do that: using DNS, `/etc/hosts`, [inetrc](http://erlang.org/doc/apps/erts/inet_cfg.html) file or a combination of the above, is up to you. This is covered in RabbitMQ documentation guides related to clustering.

Then you need to [configure your nodes to contact `etcd`](https://github.com/aweber/rabbitmq-autocluster/wiki/etcd%20Configuration) to perform discovery and enable this plugin. That's it.

If you don't know the basics of RabbitMQ cluster formation or how to configure it, it's a good idea to invest some time in [reading the docs](http://www.rabbitmq.com/) first.

**Comment by stongo** [comment]
I've been having difficulty because I'm trying to use k8s internal DNS and
end up with a chicken and egg problem. Kubernetes doesn't allow assigning a
hostname with periods (ie FQDN) so if I try using
rabbit@rabbitmq-1.default.svc.cluster.local it won't ever get set because
rabbitmq can't resolve it. And likewise if I use a shortname it's not
resolvable by DNS from other nodes.
But I'm realizing etcd backend won't help with that.
Thanks for your time with all this

**Comment by ash9002** [comment]
In the Docker Image for this https://hub.docker.com/r/gsantomaggio/rabbitmq-autocluster/ - is ETCD already installed? Or do you have to install it within each container after setting the environment variables?

**Comment by Gsantomaggio** [comment]
@ash9002 this image contains the official docker image with the [auto-cluster](https://github.com/aweber/rabbitmq-autocluster).
Since this [this PR](https://github.com/docker-library/rabbitmq/pull/121) is not merged yet, I created an image. 

It supports [these](https://github.com/aweber/rabbitmq-autocluster/wiki) backends. 


I [tested](https://www.youtube.com/watch?v=i9KH_FWJ2ek) it with ETCD2

**Comment by Gsantomaggio** [comment]
@stongo I didn't try k8s, but to setup `etcd2` as backend you just have to be sure the images can communicate through the hostnames  ( as Michael said). 

Here is a quick example using normal docker containers:
Run `etcd` ( unless you have one running)
```
./etcd  --initial-cluster-state new  \
--initial-advertise-peer-urls 'http://192.168.1.76:7001' \
--listen-peer-urls 'http://192.168.1.76:7001'  \
--listen-client-urls 'http://192.168.1.76:4001' \
--advertise-client-urls 'http://192.168.1.76:4001' \
 --data-dir=/home/gabriele/etcd2/data
```

run the fist image:
```
sudo docker run -d -p 15672:15672 -p 5672:5672 --name rabbit1 --hostname rabbitmq_node_1  -e AUTOCLUSTER_TYPE=etcd  \
-e ETCD_HOST=192.168.1.76 -e ETCD_TTL=30  -e RABBITMQ_ERLANG_COOKIE='ilovebeam' -e ETCD_PORT=4001 \
-e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false gsantomaggio/rabbitmq-autocluster
```

run the second one
```
sudo docker run -d -p 15673:15672 -p 5673:5672 --name rabbit2 --hostname rabbitmq_node_2 --link rabbit1  -e AUTOCLUSTER_TYPE=etcd  \
-e ETCD_HOST=192.168.1.76 -e ETCD_TTL=30  -e RABBITMQ_ERLANG_COOKIE='ilovebeam' -e ETCD_PORT=4001 \
-e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false gsantomaggio/rabbitmq-autocluster
````
and done!  In this case the hostname resolution is guaranteed by the `--link`.

if you use docker swarm you can use the overlay network as ` docker network create --driver overlay rabbitmq-network` 

If you still have problems let us know, we can investigate to your specific problem.

**Comment by Gsantomaggio** [comment]
Another full example here:
https://www.erlang-solutions.com/blog/scaling-rabbitmq-on-a-coreos-cluster-through-docker.html

( I think it is useful, even if it uses docker swarm )

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
