### ISSUE TITLE
Error in license?

### ISSUE THREAD

**Issue by FantasticFiasco** [aweber/rabbitmq-autocluster#115]
The license specifies the plugin name as _rabbitmq-autocluster-consul_. I am guessing that the plugin initially only targeted Consul, but has since then integrated with additional services, AWS EC2 as an example.

**Comment by michaelklishin** [comment]
I don't see [any mentions of Consul, or AWS, or specific tools and products](https://github.com/aweber/rabbitmq-autocluster/blob/master/LICENSE).

**Comment by FantasticFiasco** [comment]
> Neither the name of the rabbitmq-autocluster-__consul__

**Comment by FantasticFiasco** [comment]
I could have created a PR, but the effort for you to accept it is on the same ballpark as you fixing it yourself
