### ISSUE TITLE
See lots of 'Error updating Consul health check: "500"' messages in the logs

### ISSUE THREAD

**Issue by cap10morgan** [aweber/rabbitmq-autocluster#116]
I'm using the 0.6.1 release w/ Consul 0.7.1 and RabbitMQ 3.6.5. The cluster starts up OK, but then I see lots of messages like this in the RabbitMQ logs:

```
=ERROR REPORT==== 30-Nov-2016::17:34:10 ===
autocluster: Error updating Consul health check: "500"
```

I'm not sure how concerned I should be by that, things generally seem to work. But it doesn't fill me with confidence either.

**Comment by gmr** [comment]
My guess is you're getting a 500 error back from consul. I'd check the consul logs to see what it has to say.

**Comment by cap10morgan** [comment]
Errors from Consul log look like this:

`2016/11/30 17:36:55 [ERR] http: Request GET /v1/agent/check/pass/service%3Arabbitmq, error: CheckID "service:rabbitmq" does not have associated TTL from=172.17.0.2:34919`

**Comment by gmr** [comment]
Sorry for the delay, what version of Consul?

**Comment by cap10morgan** [comment]
0.7.1

**Comment by cap10morgan** [comment]
@Gsantomaggio Not in my case, no. Consul is running the entire time.

**Comment by michaelklishin** [comment]
Addressed in team RabbitMQ's fork: https://github.com/rabbitmq/rabbitmq-autocluster/pull/2.

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
