### ISSUE TITLE
RabbitMQ AWS AutoScaling inside a Linux AMI with private subnet in a VPC is not working

### ISSUE THREAD

**Issue by vyomtandon** [aweber/rabbitmq-autocluster#119]
**Team,**
First of all thanks for putting up this API for RabbitMQ Auto clustering. Its be many days I am trying to setup RabbitMQ Auto cluster using this plugin but with No Success.

Objective :
- I have 2 EC2 instances and want to to setup 2 rabbitmq docker cluster instances per EC2 node (total 4 docker instances).
- Once the clustering is succeeded then use ECS Registry platform to deploy the instances (again 2 docker instances per EC2).

Setup Details:
- 2 EC2 instances launched from AMI based on Amazon RHEL7.2-CIS-Bv2.1.0-Level1-Docker1.12-ECSv1.13
- Each having private subnet inside our VPC with both Amazon DNS hostname and DNS resolution set to yes.
- Using the https://github.com/gmr/alpine-rabbitmq-autocluster/ Docker Image to sping up instances.
- AWS Autoscaling group setup as the document provided in above repository.
- Docker command used for both rabbit instances
**Rabbit 1**
```
docker run --name rabbitmq -d \
  -e AUTOCLUSTER_LOG_LEVEL=debug \
  -e AUTOCLUSTER_TYPE=aws \
  -e AUTOCLUSTER_CLEANUP=true \
  -e CLEANUP_WARN_ONLY=false \
  -e AWS_DEFAULT_REGION=us-east-1 \
  -e AWS_AUTOSCALING=true \
  -p 4369:4369 \
  -p 5672:5672 \
  -p 15672:15672 \
  -p 25672:25672 \
  -h ip-10-1-46-31 \
  gavinmroy/alpine-rabbitmq-autocluster
```

**Rabbit2**
```
docker run --name rabbitmq2 -d \
  -e AUTOCLUSTER_LOG_LEVEL=debug \
  -e AUTOCLUSTER_TYPE=aws \
  -e AUTOCLUSTER_CLEANUP=true \
  -e CLEANUP_WARN_ONLY=false \
  -e AWS_DEFAULT_REGION=us-east-1 \
  -e AWS_AUTOSCALING=true \
  -p 4370:4369 \
  -p 5673:5672 \
  -p 15673:15672 \
  -p 25673:25672 \
  -h ip-10-1-46-31 \
  gavinmroy/alpine-rabbitmq-autocluster
```

- Logs for both rabbit instances
   - [Rabbitmq_Instance_1_Logs.txt](https://github.com/aweber/rabbitmq-autocluster/files/640449/Rabbitmq_Instance_1_Logs.txt)
   - [Rabbitmq_Instance_2_Logs.txt](https://github.com/aweber/rabbitmq-autocluster/files/640442/Rabbitmq_Instance_2_Logs.txt)

**Comment by vyomtandon** [comment]
Team, With some change to docker command, I am able to see the nodes forming the cluster. I have 2 Ec2 instances each having single docker instance each which joins the cluster, but another docker instance on any ec2 instances are not joining the cluster. can you point in case I am missing anything ?

![image](https://cloud.githubusercontent.com/assets/12159143/21030915/d5b16f18-bd6e-11e6-885f-1e4c46e27cfc.png)

**Cluster Status**
```
bash-4.3$ rabbitmqctl cluster_status
Cluster status of node 'rabbit@ip-10-1-46-31.ec2.internal' ...
[{nodes,[{disc,['rabbit@ip-10-1-46-31.ec2.internal', 'rabbit@ip-10-1-50-168.ec2.internal']}]},
 {running_nodes,['rabbit@ip-10-1-50-168.ec2.internal', 'rabbit@ip-10-1-46-31.ec2.internal']},
 {cluster_name,<<"rabbit@ip-10-1-50-168.ec2.internal">>},
 {partitions,[]},
 {alarms,[{'rabbit@ip-10-1-50-168.ec2.internal',[]}, {'rabbit@ip-10-1-46-31.ec2.internal',[]}]}]
bash-4.3$
```
**RabbitMQ Node 3 Docker Command :**
```
docker run --name rabbitmq -d \
  -e AUTOCLUSTER_LOG_LEVEL=debug \
  -e AUTOCLUSTER_TYPE=aws \
  -e AWS_DEFAULT_REGION=us-east-1 \
  -e AWS_AUTOSCALING=true \
  -e RABBITMQ_USE_LONGNAME=true \
  -e RABBITMQ_NODENAME=rabbit@$HOSTNAME \
  -e RABBITMQ_NODE_PORT=5674 \
  -p 4369:4369 \
  -p 5672:5672 \
  -p 15672:15672 \
  -p 25672:25672 \
  -h $HOSTNAME \
  gavinmroy/alpine-rabbitmq-autocluster
```
[Rabbitmq_Instance_3_Logs.txt](https://github.com/aweber/rabbitmq-autocluster/files/640787/Rabbitmq_Instance_3_Logs.txt)

**Comment by chb0github** [comment]
I am trying to do something nearly identical -- I am trying to do it with dns A records but I have
1) AWS VPC
2) Docker running on ec2 instance

my command:
```
docker run -d --name rabbit -e AUTOCLUSTER_HOST='queue.stage.company.com' aweber/rabbitmq-autocluster
```
I don't see them forming a cluster at all eventhough dig:

```
christian@queue4:~$ dig queue.stage.company.com

; <<>> DiG 9.9.5-3ubuntu0.10-Ubuntu <<>> queue.stage.commpany.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65009
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;queue.stage.milezero.com.	IN	A

;; ANSWER SECTION:
queue.stage.company.com. 33	IN	A	10.0.3.208
queue.stage.company.com. 33	IN	A	10.0.3.21
queue.stage.company.com. 33	IN	A	10.0.3.65

;; Query time: 0 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Mon Dec 12 07:35:44 UTC 2016
;; MSG SIZE  rcvd: 101
```

I will try what you have above since you seem to have some success

**Comment by vyomtandon** [comment]
@chb0github : Any Luck, I have 2 issues as of now, one is more than 1 containers per EC2 is not joining the clusters and I am using -h $HOSTNAME to make cluster work  this value is not passed to ECS Agent Docker Parameters as ECS Agent dosent support Dynamic values.

**Comment by chb0github** [comment]
Nope. I have had to start prototyping apache ActiveMQ -- management console
and clustering via multicast out-of-the-box -- I had a prototype of what I
need working with Rabbit, but if I can't cluster it, it's dead-in-the-water
