### ISSUE TITLE
autocluster broken on kubernetes 1.4.7

### ISSUE THREAD

**Issue by Stono** [aweber/rabbitmq-autocluster#122]
```
=INFO REPORT==== 20-Dec-2016::14:38:51 ===
autocluster: Starting k8s registration.

=INFO REPORT==== 20-Dec-2016::14:38:51 ===
autocluster: Failed to get nodes from k8s - 404

=ERROR REPORT==== 20-Dec-2016::14:38:51 ===
autocluster: Could not fetch node list from autocluster_k8s: "404".
```

RabbitMQ version 3.6.6, autocluster built from source against commit a2e2aa05598e529caa6f6c1c1f11f5346abaff4a

**Comment by michaelklishin** [comment]
There is no evidence that the plugin is "broken". A request to Kubernetes responded with a 404. There can be a myriad of reasons for that, from misconfiguration to proxies to invalid credentials to Kubernetes API bugs.

Please don't make bold claims in issue titles if you don't have any specifics to back them up.

**Comment by Stono** [comment]
Fantastic response.  Another option for your response could have been to engage with me and I'd be happy to provide whatever 'specifics' you require in order to debug the issue.

Perhaps if there are 'specifics' you require in order to debug issues, you could set up an issue template, asking for the items you need, as lets face it - I could paste 1000 different log files here as I don't know which are relevant to you.

In response to configuration, I would have said everything is the default configuration for the k8s plugin.  I would have gone on to tell you that I've validated that the url that the code appears to build, based on the default config values is `https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/thoughtdata/endpoints/rabbitmq` and a `curl -sSk -H "Authorization: Bearer $(</var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/thoughtdata/endpoints/rabbitmq` returns a valid response as expected, however when the plugin runs it's 404ing.

But alas, you're clearly hormonal - I will fork the plugin, add some more verbose log messages and fix the issue myself.

Have a great day, sir.

**Comment by michaelklishin** [comment]
@Stono or you could use sensible issue title and provided more details. You expect the maintainer or community to spend their time fixing your issue that may very well be environment-specific and provide a single log file entry then claim this project is "broken".

This is a textbook example of the [Open Source Entitlement Complex](https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d#.pphvgacz7). 
Have some decency when you expect others to spend their time fixing your stuff and provide details.

**Comment by michaelklishin** [comment]
> I will fork the plugin, add some more verbose log messages and fix the issue without your support

Good luck. If you wanted to contribute you'd have started with more information. If this issue is indeed in the plugin then someone else will report it with more details (and won't be an a-hole towards those who point out that essential information is missing).

**Comment by Stono** [comment]
@michaelklishin back to my original point and that is you're presuming that people consuming this plugin know what 'essential information' is, from your perspective.  I have no experience with erlang, and limited experience with this plugin - hence why a dialogue with me would have been great (or, as I suggested, an issue template), and I'd have answered any questions you had, instead - you decide to be pedantic and pick up on the wording used in the title of the issue.

Oh by the way, I can quote things too!!   Your responses are a classic example of [Face Time Bias](http://gsm.ucdavis.edu/blog-feature/face-time-and-unspoken-bias-behind-nontraditional-work-cultures), have some decency when people (dealing with situations you're not aware of, or from backgrounds different to yours) come seeking support.  If you're unable deal with people in a civil manner when their initial communications don't conform to your predefined definition of an acceptable message then I suggest you stay away from the internet in general as you're going to continue to get frustrated, regularly!

You calling me an 'a-hole' by the way just confirms to me the type of character that you are anyway, so as much as i'm enjoying our little dialogue, I'll bow out here and let you rage on GitHub some more, alone.

Much love.
Karl

**Comment by Gsantomaggio** [comment]
Had a similar issue.
Put the autocluster log-level to debug   `{ autocluster, debug }`  and check the HTTP calls.
Most likely some parameter is not set correctly.

**Comment by Gsantomaggio** [comment]
My problem was the `namespace` configuration on the deploy file (`rabbitmq.yaml`):

```
=DEBUG REPORT==== 15-May-2017::12:15:01 ===
autocluster: Response: [{ok,{{"HTTP/1.1",404,"Not Found"},
                             [{"date","Mon, 15 May 2017 12:15:01 GMT"},
                              {"content-length","194"},
                              {"content-type","application/json"}],
                             "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"endpoints \\\"rabbitmq\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"rabbitmq\",\"kind\":\"endpoints\"},\"code\":404}\n"}}]

=INFO REPORT==== 15-May-2017::12:15:01 ===
autocluster: Failed to get nodes from k8s - 404

=ERROR REPORT==== 15-May-2017::12:15:01 ===
autocluster: Could not fetch node list from autocluster_k8s: "404".
``` 


Fixed using:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: test-rabbitmq #the correct name space here
```

so:
```
INFO REPORT==== 15-May-2017::12:20:25 ===
autocluster: Starting k8s registration.
=DEBUG REPORT==== 15-May-2017::12:20:25 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Mon, 15 May 2017 12:20:25 GMT"},
                              {"content-length","577"},
                              {"content-type","application/json"}],
                             "{\"kind\":\"Endpoints\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"rabbitmq\",\"namespace\":\"test-rabbitmq\",\"selfLink\":\"/api/v1/namespaces/test-rabbitmq/endpoints/rabbitmq\",\"uid\":\"b256c0d9-358a-11e7-8097-080027cbdcae\",\"resourceVersion\":\"71297\",\"creationTimestamp\":\"2017-05-10T14:12:27Z\",\"labels\":{\"app\":\"rabbitmq\"}},\"subsets\":[{\"addresses\":[{\"ip\":\"172.17.0.2\",\"nodeName\":\"minikube\",\"targetRef\":{\"kind\":\"Pod\",\"namespace\":\"test-rabbitmq\",\"name\":\"rabbitmq-690681715-fp2v3\",\"uid\":\"da2ac191-3968-11e7-a2a8-080027cbdcae\",\"resourceVersion\":\"71296\"}}],\"ports\":[{\"port\":15672,\"protocol\":\"TCP\"}]}]}\n"}}]
```
