### ISSUE TITLE
Can not communicate with cluster nodes

### ISSUE THREAD

**Issue by kisev** [aweber/rabbitmq-autocluster#131]
Hi, I'm trying to use autocluster (version 0.6.1) with etcd (version 2.3.7). I have 2 nodes with host-10-100-9-26 names, host-10-100-9-20. Auto-appointed systemd names.
When rabbitmq start, the first node correctly add information about yourself in etcd, on the second node I see errors (below).

I tried to add a few records by hand, with the names 'node.ru' and 'server', they are so well-trimmed.

Thanks.

=INFO REPORT==== 2-Mar-2017::20:07:13 ===
Starting RabbitMQ 3.6.6 on Erlang 18.3.2
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 2-Mar-2017::20:07:13 ===
node           : rabbit@host-10-100-9-20
home dir       : /root
config file(s) : /opt/co/config/rabbitmq.config
cookie hash    : nhKz8+dd7aw1WRGExT1YCA==
log            : /opt/co/rabbitmq/logs/rabbit@host-10-100-9-20.log
sasl log       : /opt/co/rabbitmq/logs/rabbit@host-10-100-9-20-sasl.log
database dir   : /opt/co/rabbitmq/data/rabbit@host-10-100-9-20

=INFO REPORT==== 2-Mar-2017::20:07:15 ===
autocluster: log level set to debug

=INFO REPORT==== 2-Mar-2017::20:07:15 ===
autocluster: Using etcd backend

=INFO REPORT==== 2-Mar-2017::20:07:15 ===
autocluster: Delaying startup for 6309ms.

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: Starting etcd registration.

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: GET http://172.17.42.1:2379/v2/keys/nct%2Fco%2Frabbitmq-autocluster/co-mq-cluster?recursive=true

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 02 Mar 2017 17:07:21 GMT"},
                              {"content-length","558"},
                              {"content-type","application/json"},
                              {"x-etcd-cluster-id","cf619686c64f3b3d"},
                              {"x-etcd-index","3701"},
                              {"x-raft-index","7796"},
                              {"x-raft-term","2"}],
                             "{\"action\":\"get\",\"node\":{\"key\":\"/nct/co/rabbitmq-autocluster/co-mq-cluster\",\"dir\":true,\"nodes\":[{\"key\":\"/nct/co/rabbitmq-autocluster/co-mq-cluster/host-10-100-9-26\",\"value\":\"enabled\",\"expiration\":\"2017-03-02T17:07:38.092323902Z\",\"ttl\":17,\"modifiedIndex\":3618,\"createdIndex\":3618},{\"key\":\"/nct/co/rabbitmq-autocluster/co-mq-cluster/node.ru\",\"value\":\"enabled\",\"modifiedIndex\":1311,\"createdIndex\":1311},{\"key\":\"/nct/co/rabbitmq-autocluster/co-mq-cluster/server\",\"value\":\"enabled\",\"modifiedIndex\":3593,\"createdIndex\":3593}],\"modifiedIndex\":37,\"createdIndex\":37}}\n"}}]

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: Registering node with etcd.

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: Registered node with etcd.

=INFO REPORT==== 2-Mar-2017::20:07:21 ===
autocluster: Discovered ['rabbit@-10-100-9-26','rabbit@.ru',rabbit@er]

=ERROR REPORT==== 2-Mar-2017::20:07:31 ===
autocluster: Can not communicate with cluster nodes.

=INFO REPORT==== 2-Mar-2017::20:07:31 ===
Error description:
   {could_not_start,rabbit,
       {{case_clause,error},
        [{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]},
         {rabbit_boot_steps,run_step,2,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]},
         {rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,
             [{file,"src/rabbit_boot_steps.erl"},{line,26}]},
         {rabbit_boot_steps,run_boot_steps,1,
             [{file,"src/rabbit_boot_steps.erl"},{line,26}]},
         {rabbit,start,2,[{file,"src/rabbit.erl"},{line,687}]},
         {application_master,start_it_old,4,
             [{file,"application_master.erl"},{line,273}]}]}}

Log files (may contain more information):
   /opt/co/rabbitmq/logs/rabbit@host-10-100-9-20.log
   /opt/co/rabbitmq/logs/rabbit@host-10-100-9-20-sasl.log

**Comment by michaelklishin** [comment]
See [inter-node communication requirements](http://www.rabbitmq.com/clustering.html).
