### ISSUE TITLE
Unable to start rabbitmq server

### ISSUE THREAD

**Issue by stephenotalora** [aweber/rabbitmq-autocluster#137]
Hi,

I'm trying to start my rabbitmq server, while I can successfully build the docker image the server will always fail to boot and I get the following error description:

```
BOOT FAILED
===========

Error description:
   {error,{cannot_log_to_file,"-",{error,eacces}}}

Log files (may contain more information):
   -
   -

Stack trace:
   [{rabbit,ensure_working_log_handler,5,[]},
    {rabbit,ensure_working_log_handlers,0,[]},
    {rabbit,'-boot/0-fun-1-',0,[]},
    {rabbit,start_it,1,[]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

init terminating in do_boot ()
{"init terminating in do_boot",{rabbit,failure_during_boot,{error,{cannot_log_to_file,"-",{error,eacces}}}}}
```

I'm setting up the correct permissions as per the sample dockerfile
```
RUN chown -R rabbitmq /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq /usr/lib/rabbitmq
```

and setting the environmental variables in the same manner:
```
ENV RABBITMQ_LOGS=-
ENV RABBITMQ_SASL_LOGS=-
```

*Unlike the original dockerfile I am required to use a previous version of rabbitmq@3.3.4*

Am I missing something that would stop the server from starting correctly? 
I'm new to rabbitmq so any help would be greatly appreciated.

Thanks!

**Comment by Gsantomaggio** [comment]
In which way you are starting the Server? 
Are you trying to execute the docker image machine?

[`eacces` ](http://erlang.org/doc/man/file.html) is a permission problem
```
eacces
Missing permission for the file or one of its parents.
```

**Comment by stephenotalora** [comment]
@Gsantomaggio thanks for responding,

I'm starting the server via docker command from my **updated dockerfile** in this manner: 

1. build the image in current (project directory) `docker build -t <tag> .`
2. Once the image successfully builds I just start the docker machine: `docker run --name <image tag>` (note I'm not going into detach mode so that I can observe the output of the server starting). 

rabbitmq should start via dockerfile `CMD` when I run my container
`CMD /usr/lib/rabbitmq/sbin/rabbitmq-server`

here's a full gist of the changes I made to my [Dockerfile](https://gist.github.com/stephenotalora/000cfd8b57230261b23b03bc5be38875)

the only relevant parts that I changed from the original are:

```Dockerfile
FROM alpine:latest

ENV RABBITMQ_VERSION=3.3.4

...

RUN rabbitmq-plugins enable autocluster \
        rabbitmq_delayed_message_exchange \
        rabbitmq_management \
        rabbitmq_management_visualiser \
        rabbitmq_consistent_hash_exchange \
        rabbitmq_federation \
        rabbitmq_federation_management \
        rabbitmq_message_timestamp \
        rabbitmq_mqtt \
        rabbitmq_shovel \
        rabbitmq_shovel_management \
        rabbitmq_stomp \
        rabbitmq_top \
        rabbitmq_web_stomp && \
  rabbitmq-plugins list

RUN chown -R rabbitmq /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq /usr/lib/rabbitmq
```

also note I had to remove the following plugins:
* --offline
* rabbitmq_recent_history_exchange
* rabbitmq_sharding

If I try to build my image with the plugins above I get the following error while building: 
```

I'm not doing anything fancy yet I was just trying to start the server as a first step to get things up and running.

**Comment by michaelklishin** [comment]
`eacces` means that RabbitMQ doesn't have the permissions to write to its log file. It has nothing to do with this plugin.
