### ISSUE TITLE
EC2 Autoscaling discovery seems to not work behind corporate proxy

### ISSUE THREAD

**Issue by llarsson** [aweber/rabbitmq-autocluster#141]
This setup is admittedly convoluted, but the core issue is this: I am deploying VMs in EC2, and external traffic is forced to go through a corporate proxy. I have set the standard HTTP_PROXY, HTTPS_PROXY, and NO_PROXY variables to their correct values, but EC2 autoscaling group membership discovery fails, regardless.

I have tried downloading the latest release and running it on an Ubuntu host directly, as well as using various Docker images.

As I am not an Erlang coder, I have a hard time determining if any library used for HTTP communication needs any special configuration to honor the standard proxy-related variables. However, it seems to not work at all.

The issue is reported as `autocluster: Could not fetch node list from autocluster_aws: instance_discovery.` in the RabbitMQ log.

**Comment by michaelklishin** [comment]
EC2 discovery uses AWS-specific mechanisms that can use internal AWS networking only. How can a proxy your company has in place affect that?

**Comment by michaelklishin** [comment]
Autoscaling has to fetch current instance (VM) ID first and that's done using a well-known (and hardcoded) AWS IP. The URL is `"http://169.254.169.254/latest/meta-data/instance-id`, to be specific. If that fails, an `instance_discovery` error [is returned](https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_aws.erl#L38).

I still have no idea how these requests that only can work in an AWS environment can be affected by a corporate proxy.

**Comment by llarsson** [comment]
You set the NO_PROXY variable so that the address is excluded, however, that address is only for metadata and user data: the API calls actually happen against the AWS API endpoints.

This issue should not be closed. 

Michael Klishin <notifications@github.com> skrev: (21 mars 2017 14:26:31 CET)
>Autoscaling has to fetch current instance (VM) ID first and that's done
>using a well-known (and hardcoded) AWS IP. The URL is
>`"http://169.254.169.254/latest/meta-data/instance-id`, to be specific.
>If that fails, an `instance_discovery` error [is
>returned](https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_aws.erl#L38).
>
>I still have no idea how these requests that only can work in an AWS
>environment can be affected by a corporate proxy.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/aweber/rabbitmq-autocluster/issues/141#issuecomment-288077208

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by michaelklishin** [comment]
@llarsson this issue is a question at this point, there is no evidence that this is a bug. I close all issues that are questions so that "real" issues are easy to locate.

What "API calls" are we talking about, for example? All requests issued by this plugin are issued from RabbitMQ nodes, which are running on AWS and not your network.

Sorry but there is still not a whole lot of information about what exactly you are doing and no evidence that this is a problem in this plugin.
