### ISSUE TITLE
autocluster: Can not communicate with cluster nodes

### ISSUE THREAD

**Issue by devopsberlin** [aweber/rabbitmq-autocluster#144]
Hello
I am trying to configured Rabbitmq autocluster based upon membership in an Autoscaling Group.

I have applied the appropriate policy and I managed to create a RabbitMQ cluster manually via ` rabbitmqctl join_cluster`.

Any ideas what I'm doing wrong?

version packages:  `RabbitMQ 3.6.6 on Erlang 19.1.3`

Assign an IAM Role with the below policy to EC2 Instance and IAM user:

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "autoscaling:DescribeAutoScalingInstances",
                    "ec2:DescribeInstances"
                ],
                "Resource": [
                    "*"
                ]
            }
        ]
    }

I have the following configuration:

    [
     {rabbit,
      [
       {tcp_listeners, [5672]},
    
       %% SSL listeners are configured in the same fashion as TCP listeners,
       %% including the option to control the choice of interface.
       %%
       %% {ssl_listeners, [5671]},
    
       %% Maximum time for AMQP 0-8/0-9/0-9-1 handshake (after socket connection
       %% and SSL handshake), in milliseconds.
       %%
       %% {handshake_timeout, 10000},
    
        {log_levels, [{autocluster, debug}, {connection, info}]},
        {loopback_users, [<<"guest">>]},
    
       %% Configuring SSL.
       %% See http://www.rabbitmq.com/ssl.html for full documentation.
       %%
       %% {ssl_options, [{cacertfile,           "/path/to/testca/cacert.pem"},
       %%                {certfile,             "/path/to/server/cert.pem"},
       %%                {keyfile,              "/path/to/server/key.pem"},
       %%                {verify,               verify_peer},
       %%                {fail_if_no_peer_cert, false}]},
    
        {default_vhost,       <<"/">>},
        {default_user,        <<"ansible">>},
        {default_pass,        <<"ansible">>},
        {default_permissions, [<<".*">>, <<".*">>, <<".*">>]},
        {default_user_tags, [administrator]},
        {channel_max, 128},
    
       %% Customising Socket Options.
       %%
       %% See (http://www.erlang.org/doc/man/inet.html#setopts-2) for
       %% further documentation.
       %%
       %% {tcp_listen_options, [binary,
       %%                       {packet,        raw},
       %%                       {reuseaddr,     true},
       %%                       {backlog,       128},
       %%                       {nodelay,       true},
       %%                       {exit_on_close, false}]},
    
        {vm_memory_high_watermark, 0.4 },
        {vm_memory_high_watermark_paging_ratio, 0.5 },
    
       %% Set disk free limit (in bytes). Once free disk space reaches this
       %% lower bound, a disk alarm will be set - see the documentation
       %% listed above for more details.
       %%
       %% {disk_free_limit, 50000000},
    
          {disk_free_limit, {mem_relative, 0.7 }}
      ]},
    
      {autocluster, [
        {backend, aws},
        {aws_autoscaling, true},
        {aws_ec2_region, "eu-central-1"},
        {aws_access_key, "****"},
        {aws_secret_key, "****"}
      ]}
    
    ].  

                
        

plugin list:
    
     Configured: E = explicitly enabled; e = implicitly enabled
     | Status:   * = running on rabbit@10.80.10.243
     |/
    [e*] amqp_client                       3.6.6
    [E*] autocluster                       0.6.1
    [  ] cowboy                            1.0.3
    [  ] cowlib                            1.0.1
    [e*] mochiweb                          2.13.1
    [  ] rabbitmq_amqp1_0                  3.6.6
    [  ] rabbitmq_auth_backend_ldap        3.6.6
    [  ] rabbitmq_auth_mechanism_ssl       3.6.6
    [e*] rabbitmq_aws                      0.1.2
    [  ] rabbitmq_consistent_hash_exchange 3.6.6
    [  ] rabbitmq_event_exchange           3.6.6
    [  ] rabbitmq_federation               3.6.6
    [  ] rabbitmq_federation_management    3.6.6
    [  ] rabbitmq_jms_topic_exchange       3.6.6
    [E*] rabbitmq_management               3.6.6
    [E*] rabbitmq_management_agent         3.6.6
    [  ] rabbitmq_management_visualiser    3.6.6
    [  ] rabbitmq_mqtt                     3.6.6
    [  ] rabbitmq_recent_history_exchange  1.2.1
    [  ] rabbitmq_sharding                 0.1.0
    [  ] rabbitmq_shovel                   3.6.6
    [  ] rabbitmq_shovel_management        3.6.6
    [  ] rabbitmq_stomp                    3.6.6
    [  ] rabbitmq_top                      3.6.6
    [  ] rabbitmq_tracing                  3.6.6
    [  ] rabbitmq_trust_store              3.6.6
    [e*] rabbitmq_web_dispatch             3.6.6
    [  ] rabbitmq_web_stomp                3.6.6
    [  ] rabbitmq_web_stomp_examples       3.6.6
    [  ] sockjs                            0.3.4
    [e*] webmachine                        1.10.3
            
    
I get the following error every time in my log:
    

    =INFO REPORT==== 28-Mar-2017::02:34:54 ===
    Stopping RabbitMQ
    
    =INFO REPORT==== 28-Mar-2017::02:34:54 ===
    stopped TCP Listener on [::]:5672
    
    =INFO REPORT==== 28-Mar-2017::02:34:54 ===
    Stopped RabbitMQ application
    
    =INFO REPORT==== 28-Mar-2017::02:34:55 ===
    Starting RabbitMQ 3.6.6 on Erlang 19.1.3
    Copyright (C) 2007-2016 Pivotal Software, Inc.
    Licensed under the MPL.  See http://www.rabbitmq.com/
    
    =INFO REPORT==== 28-Mar-2017::02:34:55 ===
    node           : rabbit@10.80.10.243
    home dir       : /var/lib/rabbitmq
    config file(s) : /etc/rabbitmq/rabbitmq.config
    cookie hash    : rztAEh6FEIM8yMCIwwFtpQ==
    log            : /var/log/rabbitmq/rabbit@10.80.10.243.log
    sasl log       : /var/log/rabbitmq/rabbit@10.80.10.243-sasl.log
    database dir   : /var/lib/rabbitmq/mnesia/rabbit@10.80.10.243
    
    =INFO REPORT==== 28-Mar-2017::02:34:56 ===
    autocluster: Delaying startup for 4730ms.
    
    =INFO REPORT==== 28-Mar-2017::02:35:00 ===
    autocluster: Starting aws registration.
    
    =INFO REPORT==== 28-Mar-2017::02:35:01 ===
    autocluster: Registering node with aws.
    
    =ERROR REPORT==== 28-Mar-2017::02:35:01 ===
    autocluster: Can not communicate with cluster nodes.
    
    =INFO REPORT==== 28-Mar-2017::02:35:01 ===
    Memory limit set to 396MB of 990MB total.
    
    =INFO REPORT==== 28-Mar-2017::02:35:01 ===
    Disk free limit set to 727MB
    
    =INFO REPORT==== 28-Mar-2017::02:35:01 ===
    Limiting to approx 924 file handles (829 sockets)

First node:

    Cluster status of node 'rabbit@10.80.10.243' ...
    [{nodes,[{disc,['rabbit@10.80.10.243']}]},
     {running_nodes,['rabbit@10.80.10.243']},
     {cluster_name,<<"rabbit@10">>},
     {partitions,[]},
     {alarms,[{'rabbit@10.80.10.243',[]}]}]

	root@10:/# cat cat /etc/rabbitmq/rabbitmq-env.conf
	cat: cat: No such file or directory
	# I am a complete /etc/rabbitmq/rabbitmq-env.conf file.
	# Comment lines start with a hash character.
	# This is a /bin/sh script file - use ordinary envt var syntax
	rabbitmq_nodename=10.80.10.243
	RABBITMQ_USE_LONGNAME=true

Second node:

    Cluster status of node 'rabbit@10.80.10.144' ...
    [{nodes,[{disc,['rabbit@10.80.10.144']}]},
     {running_nodes,['rabbit@10.80.10.144']},
     {cluster_name,<<"rabbit@10">>},
     {partitions,[]},
     {alarms,[{'rabbit@10.80.10.144',[]}]}]

	root@10:/# cat /etc/rabbitmq/rabbitmq-env.conf
	# I am a complete /etc/rabbitmq/rabbitmq-env.conf file.
	# Comment lines start with a hash character.
	# This is a /bin/sh script file - use ordinary envt var syntax
	rabbitmq_nodename=10.80.10.144
	RABBITMQ_USE_LONGNAME=true

Both:

    root@10:/# cat /var/lib/rabbitmq/.erlang.cookie
    XPVTRGPZHAQYKQHKEBUF

**Comment by devopsberlin** [comment]
**Update:**

When I tried to configured the cluster based upon membership in an Autoscaling Group
```
{autocluster, [
    {backend, aws},
    {aws_autoscaling, true},
    {aws_ec2_region, "eu-central-1"},
    {aws_access_key, "****"},
    {aws_secret_key, "****"}
  ]}
```
I get the following error every time in my log:

```
=INFO REPORT==== 28-Mar-2017::01:48:16 ===
Stopping RabbitMQ

=INFO REPORT==== 28-Mar-2017::01:48:16 ===
stopped TCP Listener on [::]:5672

=INFO REPORT==== 28-Mar-2017::01:48:16 ===
Stopped RabbitMQ application

=INFO REPORT==== 28-Mar-2017::01:48:19 ===
Starting RabbitMQ 3.6.6 on Erlang 19.1.3
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 28-Mar-2017::01:48:19 ===
node           : rabbit@10.80.10.243
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : rztAEh6FEIM8yMCIwwFtpQ==
log            : /var/log/rabbitmq/rabbit@10.80.10.243.log
sasl log       : /var/log/rabbitmq/rabbit@10.80.10.243-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@10.80.10.243

=ERROR REPORT==== 28-Mar-2017::01:48:19 ===
autocluster: Backend is not configured     

```
Please help

**Comment by binarin** [comment]
Working way to enable debug log is to add the following to your env.conf (`rabbit`/`log_levels` method doesn't work since 0.6):

    export AUTOCLUSTER_LOG_LEVEL=debug

Enabling it should provide some usable diagnostics.

**Comment by michaelklishin** [comment]
You have `RABBITMQ_USE_LONGNAME` in `rabbitmq-env.conf` while it should be just `USE_LONGNAME` (the `RABBITMQ_` prefix is only used on the command line).

Closing since this is a question and there is no evidence of an issue in this plugin itself.

**Comment by devopsberlin** [comment]
@michaelklishin  I changed to `USE_LONGNAME=true` and restarted the service, but still I am getting the same error message.
@binarin I added `export AUTOCLUSTER_LOG_LEVEL=debug` to `rabbitmq-env.conf`.

I still getting the same error, do you have maybe another idea or suggestion ?
Thank you

```
=INFO REPORT==== 28-Mar-2017::09:33:58 ===
autocluster: Discovered ['rabbit@ip-10-80-10-144','rabbit@ip-10-80-10-243']

=ERROR REPORT==== 28-Mar-2017::09:33:58 ===
autocluster: Can not communicate with cluster nodes.
```

**Comment by michaelklishin** [comment]
@devopsberlin all the standard network connectivity debugging steps:

 * Stop guessing and pledge to collect as much data as possible
 * [Read what ports are used](http://www.rabbitmq.com/networking.html)
 * Check your firewalls
 * Check what interface the nodes listen on (usually all interfaces by default)
 * Check hostname resolution (every node must be able to resolve all of its peers)
 * Do a traffic capture with TCP dump and analyze it with Wireshark

**Comment by michaelklishin** [comment]
And if you are looking for help from others, post as much information as possible, for example, entire log files (or large snippets), not a couple of lines.

**Comment by devopsberlin** [comment]
@michaelklishin , thank you, but I dont think it is a network issue, I mention in my question that I managed to create a RabbitMQ cluster manually via the command line from one of the nodes `rabbitmqctl join_cluster rabbit@10.80.10.144`

**Comment by michaelklishin** [comment]
This plugin will log that it can't communicate with other nodes if it fails to contact them via `net_adm:ping/1`, which is the most simplistic way of checking inter-node connectivity in Erlang:
https://github.com/aweber/rabbitmq-autocluster/blob/9ed821379c370ca1ce8e4a2dd55501fcf76d4e65/src/autocluster.erl#L325.
Nothing particularly creative.

We see that peer discovery does succeed as 2 other node names are logged.

Do all nodes use `USE_LONGNAME`?

This fork is currently not getting much attention. You can try building from https://github.com/rabbitmq/rabbitmq-autocluster (from the stable branch), or we can upload a build here as we are working through the list of issues specific to AWS.

**Comment by michaelklishin** [comment]
Your node logs that its name is `rabbit@10.80.10.243` but private IP hostnames are discovered: `'rabbit@ip-10-80-10-243'`. That's a hostname mismatch that will fail inter-node authentication.

**Comment by devopsberlin** [comment]
I have 2 nodes in the ASG

Node 1:
```
# I am a complete /etc/rabbitmq/rabbitmq-env.conf file.
# Comment lines start with a hash character.
# This is a /bin/sh script file - use ordinary envt var syntax
rabbitmq_nodename=10.80.10.243
#rabbitmq_nodename=node2
USE_LONGNAME=true
export AUTOCLUSTER_LOG_LEVEL=debug
```

Node 2:

```
# I am a complete /etc/rabbitmq/rabbitmq-env.conf file.
# Comment lines start with a hash character.
# This is a /bin/sh script file - use ordinary envt var syntax
rabbitmq_nodename=10.80.10.144
#rabbitmq_nodename=node1
#RABBITMQ_USE_LONGNAME=true
USE_LONGNAME=true
export AUTOCLUSTER_LOG_LEVEL=debug 
```

**Comment by michaelklishin** [comment]
…and when you manually cluster, you use an IP address, not a private EC2 network hostname: `rabbitmqctl join_cluster rabbit@10.80.10.144`.

So `rabbit@10.80.10.144` is reachable (as in network + Erlang inter-node authentication) but `rabbit@ip-10.80.10.144` is not.

**Comment by binarin** [comment]
You should read https://www.rabbitmq.com/configure.html#define-environment-variables more carefully. According to it 

    rabbitmq_nodename=10.80.10.144

is completely wrong when used in `rabbitmq-env.conf` file (lower/upper case, `rabbitmq_ ` prefix and the name itself should have `@` somewhere)

**Comment by devopsberlin** [comment]
Weird, do you know maybe from where it take `ip-10.80.10.144` ? so from what I understand it should be `10.80.10.144` ?

```
root@rabbit1:~# hostname -f
10.80.10.144
```

**Comment by devopsberlin** [comment]
@binarin checking , thanks guys!

**Comment by michaelklishin** [comment]
From [EC2 documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#concepts-private-addresses):

```
When you launch an instance, we allocate a private IPv4 address for the instance using DHCP.
Each instance is also given an internal DNS hostname that resolves to the private IPv4 address of the instance; for example, ip-10-251-50-12.ec2.internal. You can use the internal DNS hostname
for communication between instances in the same network, but we can't resolve
the DNS hostname outside the network that the instance is in.
```

Internal EC2 DNS is optimal for scenarios such as inter-node communication and peer discovery, à la what this plugin does. You just need to make sure that your nodes have a correct (matching) node name. With tools such as Ansible or Chef or Puppet or BOSH it should be reasonably straightforward.

**Comment by devopsberlin** [comment]
@michaelklishin @binarin I am using ansible and I changed the /etc/hostname, /etc/hosts, but it always retrieves the value of private dns field something like ip-192-168-x-xx., I have the same issue like #114  `https://github.com/aweber/rabbitmq-autocluster/issues/114`
