### ISSUE TITLE
ECS Task Role throwing a "forbidden" error with ASG clustering

### ISSUE THREAD

**Issue by ml019** [aweber/rabbitmq-autocluster#146]
I've been successfully using the docker image at https://hub.docker.com/r/gavinmroy/alpine-rabbitmq-autocluster/ for over 12 months to perform ASG based clustering but have found it has stopped working when I switched to using task based IAM roles (as opposed to instance based roles). I've confirmed via aws cli in the container that I can access the two AWS services required, so the IAM setup is ok I think.

I went to try a more recent image but found both the latest version of the image I am using and the aweber/rabbitmq-autocluster image are both over 10 months old. 

Any chance of a refresh so I can confirm if the problem goes away with a later image (and hence later versions of everything) ?

Thanks

**Comment by ml019** [comment]
I'm thinking I need a build with a later version of the SDK, as support for ECS task roles was added since the comtainer was built...

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
