### ISSUE TITLE
EC2 Autoscaling fail connect autoscaling.cn-north-1.amazonaws.com

### ISSUE THREAD

**Issue by CoastWe** [aweber/rabbitmq-autocluster#148]
When I use this plugin on Amazon's cn-north-1 autoscaling group, I found that the address he requested was autoscaling.cn-north-1.amazonaws.com. But this address is wrong, the correct address is autoscaling.cn-north-1.amazonaws.com.cn. next I should do!

`Error description:
   {could_not_start,rabbit,
       {{function_clause,
            [{rabbitmq_aws,format_response,
                 [{error,
                      {failed_connect,
                          [{to_address,
                               {"autoscaling.cn-north-1.amazonaws.com",443}},
                           {inet,[inet],nxdomain}]}}],
                 [{file,"src/rabbitmq_aws.erl"},{line,229}]},
             {rabbitmq_aws,perform_request_with_creds,7,
                 [{file,"src/rabbitmq_aws.erl"},{line,404}]},
             {rabbitmq_aws,handle_call,3,
                 [{file,"src/rabbitmq_aws.erl"},{line,164}]},
             {gen_server,try_handle_call,4,
                 [{file,"gen_server.erl"},{line,629}]},
             {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},
             {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},
        {gen_server,call,
            [rabbitmq_aws,
             {request,"autoscaling",get,[],
                 "/?Action=DescribeAutoScalingInstances&Version=2011-01-01",
                 [],[],undefined}]}}}
`

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
