### ISSUE TITLE
config file location 

### ISSUE THREAD

**Issue by amitgilad3** [aweber/rabbitmq-autocluster#15]
Hi ,
its my first time trying this plugin and i cant figure out were to put the config file.
do i need to put it inside the autocluster-0.4.0.ez or do i need to put it in the plugins dir?

**Comment by shanielh** [comment]
Hi Amit, Are you using `rabbitmq-autocluster` with `rabbitmq`? If yes. You should change the rabbitmq configuration file.example is found [here](https://github.com/aweber/rabbitmq-autocluster#example-rabbitmqconfig).

**Comment by amitgilad3** [comment]
hi shani,

thanks for the help .
everything worked :)
