### ISSUE TITLE
auto-clustering not starting

### ISSUE THREAD

**Issue by dimon8829** [aweber/rabbitmq-autocluster#150]
Hello,
I am trying to use the rabbitmq-autocluster plugin in Consul. 
My config rabbitmq:
`{autocluster,
  [
    {consul_host, "localhost"},
    {consul_port, 8500},
    {consul_service, "rabbitmq"},
    {cluster_name, "depohost"},
    {backend, "consul"}
  ]}`

I have following errors:

=CRASH REPORT==== 4-Jul-2017::23:22:03 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.176.0>
    registered_name: []
    exception exit: {bad_return,
                        {{rabbit,start,[normal,[]]},
                         {'EXIT',
                             {undef,
                                 [{crypto,rand_bytes,"\f",[]},
                                  {autocluster,startup_delay,1,
                                      [{file,"src/autocluster.erl"},
                                       {line,347}]},
                                  {autocluster,ensure_registered,2,
                                      [{file,"src/autocluster.erl"},
                                       {line,95}]},
                                  {autocluster,init,0,
                                      [{file,"src/autocluster.erl"},
                                       {line,33}]},
                                  {rabbit_boot_steps,
                                      '-run_step/2-lc$^1/1-1-',1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,49}]},
                                  {rabbit_boot_steps,run_step,2,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,49}]},
                                  {rabbit_boot_steps,
                                      '-run_boot_steps/1-lc$^0/1-0-',1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,26}]},
                                  {rabbit_boot_steps,run_boot_steps,1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,26}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 134)
    ancestors: [<0.175.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.177.0>,normal}]
    links: [<0.175.0>,<0.33.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 157
  neighbours:

**Comment by Gsantomaggio** [comment]
The problem is not the autocluster but:
```
{undef,
[{crypto,rand_bytes,"\f",[]},
```
your Erlang installation is not complete.

you should install the `crypto` module, for ex: `sudo apt-get install erlang-crypto`

**Note:** [This fork is currently not under active development](https://github.com/aweber/rabbitmq-autocluster#project-maturity-and-status)

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
