### ISSUE TITLE
Please support microsoft service fabric on linux and maybe windows too

### ISSUE THREAD

**Issue by AceHack** [aweber/rabbitmq-autocluster#151]
Service fabric supports running on Linux, it can run docker containers, it has a service discovery service named the naming service much like consul and it can even run docker compose files and it even has it's own DNS service that can facilitate service discovery based on the state in the naming service. Please add this is a supported backend, it would be amazing.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services

**Comment by AceHack** [comment]
Here is a windows nanoserver-insider docker image for rabbit if that helps getting it supported on windows at all.
[rabbitmq-nanoserver-insider.zip](https://github.com/aweber/rabbitmq-autocluster/files/1289341/rabbitmq-nanoserver-insider.zip)

**Comment by gmr** [comment]
The RabbitMQ team now maintains the plugin @ https://github.com/rabbitmq/rabbitmq-autocluster -- Mind closing this out and opening your feature request there?  Thanks!

**Comment by AceHack** [comment]
Thanks I created an issue there
