### ISSUE TITLE
RabbitMQ Unable to Communicate with Other Nodes

### ISSUE THREAD

**Issue by celestialorb** [aweber/rabbitmq-autocluster#154]
I have a cluster of EC2 instances setup with a `service` tag that allows RabbitMQ to identify cluster nodes (and is properly able to), however when attempting to communicate with the nodes RabbitMQ encounters an error:

```
autocluster: List of registered nodes retrieved from the backend: ['rabbit@ip-<address1>',
'rabbit@ip-<address2>',
'rabbit@ip-<address3>']

autocluster: Fetching node details. Responses: [{badrpc,
{'EXIT',
{noproc,
{gen_server,call,
[rabbit_node_monitor,
partitions,infinity]}}}}]
```

Google turned up nothing, so I'm not sure where to start.  I've opened up all ports on my EC2 instances thinking I had forgotten a port, but that hasn't helped.  Any ideas?

**Comment by baldoalessandro** [comment]
Same here:

```
[{badrpc,
 {'EXIT',
  {noproc,
   {gen_server,call,
    [rabbit_node_monitor,
     partitions,infinity]}}}},
{candidate_seed_node,
 'rabbit@ip-172-253-27-109.eu-west-1.compute.internal',
 3702163,true,
 ['rabbit@ip-172-253-15-52.eu-west-1.compute.internal',
  'rabbit@ip-172-253-27-109.eu-west-1.compute.internal'],
 ['rabbit@ip-172-253-27-109.eu-west-1.compute.internal'],
 [],[]}]
```

RabbitMQ 3.6.12 on Erlang 18.3

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
