### ISSUE TITLE
Disconnecting Rabbit MQ Nodes from Cluster?

### ISSUE THREAD

**Issue by shanielh** [aweber/rabbitmq-autocluster#17]
Hi.

Is there a way to "disconnect" a node from cluster? 

(I'm using rabbitmq-autocluster 0.3.1 with consul)

**Comment by gmr** [comment]
Not in the plugin, I intentionally kept it "simple" and wanted to not change the default clustering behavior with regard to breaking up clusters. "Breaking up a cluster" at http://www.rabbitmq.com/clustering.html describes the process, but basically if the node is no longer available, it's using ``rabbitmqctl`` on a running node to run the ``forget_cluster_node`` command.

I figured it'd be a bad thing to automate the removal of cluster nodes.

**Comment by shanielh** [comment]
Ok. Thanks. 



—

שני.
