### ISSUE TITLE
management plugin crash when re-joining existing cluster

### ISSUE THREAD

**Issue by efii** [aweber/rabbitmq-autocluster#20]
This is problem doesn't seem to be fixed: https://github.com/aweber/rabbitmq-autocluster/issues/5

I am seeing this with 0.4.1 and RMQ 3.5.3 (not 100% of the time). To fix it, I have to manually forget_cluster_node on a clustered instance, and kill epmd and clear out ~rabbitmq/mnesia on the crashed instance. Is there any way to automatically force a forget_cluster_node on a non-responding node?

**Comment by gmr** [comment]
Can you provide the SASL logs on the crashing node?

**Comment by efii** [comment]
=SUPERVISOR REPORT==== 10-Sep-2015::20:44:16 ===
     Supervisor: {local,rabbit_mgmt_sup}
     Context:    child_terminated
     Reason:     {shutdown,[{{already_started,<22643.359.0>},
                             {child,undefined,rabbit_mgmt_db,
                                    {rabbit_mgmt_db,start_link,[]},
                                    permanent,4294967295,worker,
                                    [rabbit_mgmt_db]}}]}
     Offender:   [{pid,<0.528.0>},
                  {name,mirroring},
                  {mfargs,
                      {mirrored_supervisor,start_internal,
                          [rabbit_mgmt_sup,
                           #Fun<rabbit_misc.execute_mnesia_transaction.1>,
                           [{rabbit_mgmt_db,
                                {rabbit_mgmt_db,start_link,[]},
                                permanent,4294967295,worker,
                                [rabbit_mgmt_db]}]]}},
                  {restart_type,permanent},
                  {shutdown,4294967295},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 10-Sep-2015::20:44:16 ===
     Supervisor: {local,rabbit_mgmt_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.528.0>},
                  {name,mirroring},
                  {mfargs,
                      {mirrored_supervisor,start_internal,
                          [rabbit_mgmt_sup,
                           #Fun<rabbit_misc.execute_mnesia_transaction.1>,
                           [{rabbit_mgmt_db,
                                {rabbit_mgmt_db,start_link,[]},
                                permanent,4294967295,worker,
                                [rabbit_mgmt_db]}]]}},
                  {restart_type,permanent},
                  {shutdown,4294967295},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 10-Sep-2015::20:44:16 ===
     Supervisor: {local,rabbit_mgmt_sup_sup}
     Context:    start_error
     Reason:     {'EXIT',
                     {{shutdown,
                          [{{already_started,<22643.359.0>},
                            {child,undefined,rabbit_mgmt_db,
                                {rabbit_mgmt_db,start_link,[]},
                                permanent,4294967295,worker,
                                [rabbit_mgmt_db]}}]},
                      {gen_server2,call,
                          [<0.528.0>,{init,<0.526.0>},infinity]}}}
     Offender:   [{pid,undefined},
                  {name,rabbit_mgmt_sup},
                  {mfargs,{rabbit_mgmt_sup,start_link,[]}},
                  {restart_type,temporary},
                  {shutdown,4294967295},
                  {child_type,supervisor}]


=CRASH REPORT==== 10-Sep-2015::20:44:16 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.506.0>
    registered_name: []
    exception exit: {{shutdown,
                      {failed_to_start_child,rabbit_mgmt_sup,
                       {'EXIT',
                        {{shutdown,
                          [{{already_started,<22643.359.0>},
                            {child,undefined,rabbit_mgmt_db,
                             {rabbit_mgmt_db,start_link,[]},
                             permanent,4294967295,worker,
                             [rabbit_mgmt_db]}}]},
                         {gen_server2,call,
                          [<0.528.0>,{init,<0.526.0>},infinity]}}}}},
                     {rabbit_mgmt_app,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 133)
    ancestors: [<0.505.0>]
    messages: [{'EXIT',<0.507.0>,normal}]
    links: [<0.505.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 126
  neighbours:

**Comment by gmr** [comment]
Thanks for the log snippet, that's helpful but doesn't exactly explain the why. The normal rabbitmq log on startup could help as well.

I've intentionally not made "forcing" a thing -- but if we can frame it in a way that is only destructive when it's appropriate, I'm game.

Is there anything custom about your setup? What erlang version are you using? You're using the Consul backend?  To get in this state, the node first has to crash, or is it just a reboot of a node in the cluster? I'd be good to figure out the circumstances that are happening.

**Comment by efii** [comment]
Nothing custom, although I'm not running it as a container, but on an ubuntu instance configured with chef.  Linux distro is ubuntu 14.04.2 LTS, consul version is 0.5.2.

It doesn't seem to occur after a clean shutdown and restart of either the rabbitmq server or the entire linux instance (which presumably shuts down rabbitmq cleanly).  It occurs infrequently after a crash and almost always if destroy the instance and boot a new one to replace it.

==> /etc/rabbitmq/enabled_plugins <==
[autocluster,rabbitmq_management].

==> /etc/rabbitmq/rabbitmq.config <==
[{rabbit, [{loopback_users, []}]}].




     "Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:30] [kernel-poll:true]\n"},

# cat rabbit@rabbitmq-cluster2-ubuntu-1404.log

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Starting RabbitMQ 3.5.3 on Erlang R16B03
Copyright (C) 2007-2014 GoPivotal, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
node           : rabbit@rabbitmq-cluster2-ubuntu-1404
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : 3fu3gpuV4imrYOD7OMXfBg==
log            : /var/log/rabbitmq/rabbit@rabbitmq-cluster2-ubuntu-1404.log
sasl log       : /var/log/rabbitmq/rabbit@rabbitmq-cluster2-ubuntu-1404-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cluster2-ubuntu-1404

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
autocluster: Registering node with consul

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Resetting Rabbit

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Already member of cluster: ['rabbit@rabbitmq-cluster2-ubuntu-1404',
                            'rabbit@rabbitmq-cluster3-ubuntu-1404',
                            'rabbit@rabbitmq-cluster1-ubuntu-1404']

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Memory limit set to 1581MB of 3953MB total.

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Disk free limit set to 50MB

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Limiting to approx 924 file handles (829 sockets)

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Management plugin: using rates mode 'basic'

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 10-Sep-2015::23:03:46 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Adding vhost '/'

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Creating user 'guest'

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 10-Sep-2015::23:03:46 ===
autocluster: Starting Consul Health Check TTL Timer

=INFO REPORT==== 10-Sep-2015::23:03:47 ===
Management plugin started. Port: 15672

=INFO REPORT==== 10-Sep-2015::23:03:47 ===
stopped TCP Listener on [::]:5672

=INFO REPORT==== 10-Sep-2015::23:03:47 ===
Error description:
   {could_not_start,rabbitmq_management,
       {{shutdown,
            {failed_to_start_child,rabbit_mgmt_sup,
                {'EXIT',
                    {{shutdown,
                         [{{already_started,<22646.1897.0>},
                           {child,undefined,rabbit_mgmt_db,
                               {rabbit_mgmt_db,start_link,[]},
                               permanent,4294967295,worker,
                               [rabbit_mgmt_db]}}]},
                     {gen_server2,call,
                         [<0.520.0>,{init,<0.518.0>},infinity]}}}}},
        {rabbit_mgmt_app,start,[normal,[]]}}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@rabbitmq-cluster2-ubuntu-1404.log
   /var/log/rabbitmq/rabbit@rabbitmq-cluster2-ubuntu-1404-sasl.log

**Comment by patrickhwood** [comment]
Is there a way to pass arguments to a plugin?  A way to enable/disable forcing a forget_cluster_node when a different one (or at least one that rabbitmq *thinks* is different) with the same name attempts to join the cluster?  That seems to be what's happening in my case, and since I control the node names, I know that I'll never have a new one with the same name as an old one unless the old one is toast.

**Comment by Giri-Chintala** [comment]
i am facing very similar issue #44.
It seems there are multiple issue in the scenario when a terminated/crashed node re-joining same existing cluster. 

1. First One: Management plug-in crashes as  it is trying to start mgmt_db, but DB was already started ( due to some [race condition??](https://groups.google.com/forum/#!topic/rabbitmq-users/sjyTbQzB-Dw)).
  - i resolved it by disabling mgmt-plugin and enable it again. able to successfully start re-joining rabbit node.

2. Second One (seems to be rabbitmq bug) : even though re-joining node is started successfully,  it didn't actually join existing cluster on join_cluster() call.  Because, Existing cluster thinks that re-joining node is Already member of cluster, but re-joining node doesn't have any knowledge of cluster as the  node was member of the cluster some time back, got terminated/crashed, and trying to start as a fresh rabbit node.

i think RabbitMQ should be intelligent enough to  join cluster and re-joining node, as re-joining node starting as fresh one.


Steps to reproduce Issue 2: 
1.  Start Node A, Start Node B.
2.  Join B with Node A.
3.  Terminate B (either kill,power-off B. not rabbitmqctl stop)
4. re-create Host B, and try to join A.

**Comment by efii** [comment]
Fixed in 0.5.1-pr1
