### ISSUE TITLE
Error bringing up subsequent docker containers

### ISSUE THREAD

**Issue by betht1220** [aweber/rabbitmq-autocluster#26]
-----no port specified
docker run -d -p 15672:15672 --dns 127.0.0.1 --dns-search node.rmq.consul aweber/rabbitmq-autocluster

WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
9a3b5b0586cb9580f873f2daf1c8583a9f6df12e9975a359192dfa7e7bb389cd

-------- I tried specifying the port as below
docker run -d -p 15672:15672 --dns 127.0.0.1 --dns-search node.rmq.consul aweber/rabbitmq-autocluster-consul
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
9c45b49a5017b9b80ce1e929d02ad3f78ff94109e99e0de3225886f4397c8d19
Error response from daemon: Cannot start container 9c45b49a5017b9b80ce1e929d02ad3f78ff94109e99e0de3225886f4397c8d19: Bind for 0.0.0.0:15672 failed: port is already allocated

**Comment by gmr** [comment]
That means that you're asking docker to expose port 15672 as port 15672 on more than one container, which it will not do. Both of your examples in ``-p 15672:15672``.
