### ISSUE TITLE
Add a tutorial

### ISSUE THREAD

**Issue by thedrow** [aweber/rabbitmq-autocluster#27]
This project is useful and would be easier to use if a step by step tutorial would guide the users on how to set this up on all backends and test it.

**Comment by hamx0r** [comment]
It would also be great to to know how one can check the cluster status.  For the [native clustering](https://www.rabbitmq.com/clustering.html) and [`clusterer` plugin](https://github.com/rabbitmq/rabbitmq-clusterer), `rabbitmqctl cluster_status` checks.   Is it sufficient to check if Console sees the right number of nodes to know the cluster status?  

Likewise, the other two clustering methods are known to rely on host reachability via DNS or /etc/hosts.  Is this also a requirement for `autocluster`?   The hope with using it is to eliminate needing to push unique configs onto each RMQ instance, and instead have them all point to the same Consul instance be done.

**Comment by j-fernandes** [comment]
Second this

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
