### ISSUE TITLE
Add a kubernates backend

### ISSUE THREAD

**Issue by thedrow** [aweber/rabbitmq-autocluster#28]
A kubernates backend should be able to manage volumes as well and that will assist in moving RabbitMQ servers that have persistent queues.

**Comment by altvnk** [comment]
+1

**Comment by altvnk** [comment]
Anyway if it's possible to use node addresses, then clustering can happen right now, because each k8s pod has own IP address, but doesn't have cluster-wide domain name.

**Comment by michaelklishin** [comment]
Erlang assumes node names are resolvable. When DNS or `/etc/hosts` is not an option, you can use any other [local file or a combination of resolvers](http://www.erlang.org/doc/apps/erts/inet_cfg.html).

**Comment by altvnk** [comment]
Oh, right. I missed this point. 
Well, then provider for Kubernetes is still good idea, not sure how to deal with missing pod DNS names. Probably additional configuration inside container is needed.

**Comment by dhart-alldigital** [comment]
+1

**Comment by spiddy** [comment]
+1 for Kubernetes Backend. Also, does this plugin handles the IP-to-ErlangNodes translation using the local file config mentioned above or it assumes DNS resolution?

**Comment by michaelklishin** [comment]
@spiddy see the link above. It's hostname to IP that's resolved by Erlang nodes, usually not the other way around. What this plugin does is completely orthogonal to that and can be considered a part of the runtime.

**Comment by binarin** [comment]
With https://github.com/rabbitmq/rabbitmq-server/pull/892/files it'll be possible to cluster nodes using IP addresses only.

**Comment by Nagodar** [comment]
I've not tried it, but the dns backend should work with kubernetes petset because they have pod dns resolution:

http://kubernetes.io/docs/user-guide/petset/

**Comment by gmr** [comment]
The issue becomes that the DNS name of the Docker container that is running must be resolvable for all RabbitMQ nodes, for them to speak together. It can not be the name of the machine that the docker containers are running against.

AFAIK the only way this can be achieved in Docker is to use host networking for the node it's on.

**Comment by Nagodar** [comment]
With kubernetes petset you know exactly every docker container hostname and they are resolvable by the kubernetes dns, thats why I think it should work.

Regards

**Comment by xek** [comment]
In my proposed solution, I setup RabbitMQ with:
RABBITMQ_USE_LONGNAME=true
RABBITMQ_NODENAME=rabbit@`hostname --ip-address`

**Comment by gmr** [comment]
I'll try and find time soon to build a preview release for the next version with the new PR that was just merged adding support.

**Comment by AndrewDryga** [comment]
+1
