### ISSUE TITLE
Separate 3.5.x and master branches

### ISSUE THREAD

**Issue by michaelklishin** [aweber/rabbitmq-autocluster#34]
This would make it possible to move master to RabbitMQ's new, erlang.mk-based build system.

**Comment by gmr** [comment]
I'll split out the branches after the next release addressing the current open issues.

**Comment by michaelklishin** [comment]
Note: `stable` in RabbitMQ repositories now uses `erlang.mk`, so if you want to build a release against `3.5.x` you need to check out the `3.5.7` tag.
