### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by scalp42** [aweber/rabbitmq-autocluster#36]
Following the build steps:

```
Makefile:1: ../umbrella.mk: No such file or directory
make: *** No rule to make target `../umbrella.mk'.  Stop.
```

Any ideas @gmr  ?

**Comment by scalp42** [comment]
Looks like you need to checkout `stable` branch for umbrella repo.

**Comment by michaelklishin** [comment]
Note: `stable` in RabbitMQ repositories now uses `erlang.mk`, so if you want to build a release against `3.5.x` you need to check out the `3.5.7` tag.

**Comment by gmr** [comment]
I'll be checking in my branch that works with 3.6+ soon
