### ISSUE TITLE
AUTOCLUSTER_TYPE var is being ignored

### ISSUE THREAD

**Issue by scalp42** [aweber/rabbitmq-autocluster#37]
Content of `rabbitmq-env.config`:

```
root@rabbitmq-i-bc37e966 ~ # cat /etc/rabbitmq/rabbitmq-env.conf
###
# Generated by Chef
###


NODENAME=rabbit@ec2-54-200-200-176.us-west-2.compute.amazonaws.com

CONFIG_FILE=/etc/rabbitmq/rabbitmq

MNESIA_BASE=/rabbitmq/mnesia
SERVER_ADDITIONAL_ERL_ARGS='+A 30'

# Additional ENV settings
RABBITMQ_USE_LONGNAME=true
RABBITMQ_BASE=/rabbitmq
AUTOCLUSTER_HOST=gz-dev.rabbitmq.service.consul
AUTOCLUSTER_TYPE=dns
CLUSTER_NAME=chat
CONSUL_SERVICE=rabbitmq-chat
```

Log when RabbitMQ starts:

```
=INFO REPORT==== 16-Dec-2015::21:59:21 ===
autocluster: Registering node with consul

=ERROR REPORT==== 16-Dec-2015::21:59:22 ===
** System running to use fully qualified hostnames **
** Hostname gz-dev2-data-i-d4d0e410 is illegal **
```

It looks like the `dns` backend is being ignored and is defaulting to `consul` backend.

**Comment by scalp42** [comment]
They might be all ignored actually.

**Comment by rschwiebert** [comment]
@scalp42 This might be your problem. From the docs here: https://www.rabbitmq.com/configure.html

On Unix-based systems (including Linux, MacOSX) you can create/edit rabbitmq-env.conf to define environment variables. Its location is not configurable (unlike rabbitmq.config).

Use the standard environment variable names (but **drop the RABBITMQ_ prefix**) e.g.

**Comment by mgoldsborough** [comment]
I"m actually experiencing the same issue:

```
root@c1710a1657ef:~# export AUTOCLUSTER_TYPE=etcd
root@c1710a1657ef:~# export ETCD_HOST=192.168.99.100
root@c1710a1657ef:~# echo $AUTOCLUSTER_TYPE
etcd
root@c1710a1657ef:~# echo $ETCD_HOST
192.168.99.100


root@c1710a1657ef:~# rabbitmq-plugins enable autocluster
The following plugins have been enabled:
  autocluster

Applying plugin configuration to rabbit@c1710a1657ef...
=ERROR REPORT==== 8-Mar-2016::19:40:50 ===
autocluster: HTTP Error {failed_connect,
                            [{to_address,{"localhost",8500}},
                             {inet,[inet],econnrefused}]}

=ERROR REPORT==== 8-Mar-2016::19:40:50 ===
autocluster: Could not fetch node list from autocluster_consul: {failed_connect,
                                                                 [{to_address,
                                                                   {"localhost",
                                                                    8500}},
                                                                  {inet,
                                                                   [inet],
                                                                   econnrefused}]}

=INFO REPORT==== 8-Mar-2016::19:40:50 ===
autocluster: Error in ensuring clustered

=INFO REPORT==== 8-Mar-2016::19:40:50 ===
autocluster: Starting Consul Health Check TTL Timer
 started 1 plugin.
root@c1710a1657ef:~# 
=INFO REPORT==== 8-Mar-2016::19:40:50 ===
Plugins changed; enabled [autocluster], disabled []
```

It's using consul regardless of the ```AUTOCLUSTER_TYPE``` env var.

**Comment by rschwiebert** [comment]
I don't get errors like that (using dns) but then again I can't cluster at all, so it might be related.

**Comment by mgoldsborough** [comment]
When you enable the plugin, is it recognizing that you are using DNS or does it default to consul? If so, how are you configuring your environment? rabbitmq.config or env vars? Thanks!

**Comment by rschwiebert** [comment]
@mgoldsborough Are you asking anyone specifically? If the Consul health check in my log is any indication, it might be defaulting to consul. Can you recommend a different way to check?

**Comment by gmr** [comment]
The plugin does not support the rabbit-env.conf file. If you use the environment variable ``RABBITMQ_USE_LONGNAME`` variable as an environment variable, it will work. Also note that I believe the syntax for the rabbit-env.conf file is to chop off the ``RABBITMQ_`` prefix.

I've opened a ticket (#59) to support rabbit-env.conf configuration.
