### ISSUE TITLE
Autocluster for latest RabbitMQ

### ISSUE THREAD

**Issue by shunanya** [aweber/rabbitmq-autocluster#39]
The [RabbitMQ](https://www.rabbitmq.com/community-plugins.html) site is declares that "autocluster has not yet been built for v3.6.x". Can you please inform when will be ready the autocluster support for the latest 3.6.x RabbitMq version?

**Comment by AVVS** [comment]
@gmr any idea when this would happen or what steps need to be done in oder to get this working? I'm not really familiar with erlang so it's quite hard for me to do a PR myself :(

**Comment by gmr** [comment]
I'll try and get to the repo changes required as mentioned in #34 this weekend.

**Comment by AVVS** [comment]
Cool :+1:

**Comment by magec** [comment]
:+1:

**Comment by AVVS** [comment]
@gmr any update?

**Comment by zonzamas** [comment]
Looking forward for this :+1:

**Comment by gmr** [comment]
I have the build working and have some outstanding bugs to fix from PRs that looked good when I merged them but broke things.

**Comment by mgoldsborough** [comment]
:+1:

**Comment by burdandrei** [comment]
@gmr, Great! looking forward see it working!

**Comment by adamlc** [comment]
Also looking forward to this 👍

**Comment by scopenco** [comment]
waiting too

**Comment by nikiwiles** [comment]
Looking forward to this.

**Comment by gmr** [comment]
Sorry for the delay, it's coming along.

**Comment by gmr** [comment]
0.5.0 will be released within the week.

**Comment by gmr** [comment]
This is released.
