### ISSUE TITLE
Auto cluster with EC2 Auto-scale group

### ISSUE THREAD

**Issue by Giri-Chintala** [aweber/rabbitmq-autocluster#43]
I am trying to create RabbitMQ cluster using auto-cluster, consul and EC2 instances created using EC2-Auto-Scale min size 2 and max size 3.    

EC2 launched two instances at around same time(few millisecond difference), unfortunately auto-cluster plug-in in each EC2 instance thought that it is the first node in the cluster and finally cluster is not formed.

--------------------------------------------------------------------------------------
EC2 Instance 1
--------------------------------------------------------------------------------------
=INFO REPORT==== 25-Jan-2016::23:00:44 ===
autocluster: Registering node with consul
=INFO REPORT==== 25-Jan-2016::23:00:44 ===
autocluster: Node appears to be the first in the cluster
--------------------------------------------------------------------------------------
EC2 Instance 2
--------------------------------------------------------------------------------------
=INFO REPORT==== 25-Jan-2016::23:00:42 ===
autocluster: Registering node with consul

=INFO REPORT==== 25-Jan-2016::23:00:42 ===
autocluster: Node appears to be the first in the cluster

**Comment by michaelklishin** [comment]
That's an inherent race condition with autoscaling groups. Injecting random delays into startup scripts is a common workaround.

**Comment by michaelklishin** [comment]
Note: this plugin *cannot* work around this without introducing some kind of preference for nodes, which with autoscaling groups won't work very well anyway as nodes change over time. Your deployment tools can and should.

**Comment by Giri-Chintala** [comment]
randomly delay may ran in to same race condition occasionally. 

i tried to solve it updating autoscale group size and it worked. 
First, start with autoscale group with min size 1, once first node is successfully luanched, update auto scale size to desired size (3). all the new ec2 instances joined cluster with first instance.

**Comment by michaelklishin** [comment]
@Giri-Chintala you are right, it might. And yes, gradually increasing autoscaling group size will help but it is a pain in the neck to automate things that way.

**Comment by TMiNus** [comment]
in we introduce a **health check**, this problem could be solved. Lets say we launch 3 nodes at the same time, each of those nodes thinks it is the first one in the cluster, so in etcd we will have 3 independent nodes, it is pretty easy to realize that something is wrong if we compare the size of the cluster and the amount on nodes registered in etcd. After we compare the size of the cluster and the amount of nodes registered in etcd we can pick one master at random or do some  algorithm to pick a master (aka quorum).

**Comment by gmr** [comment]
I have added a randomized startup delay into 0.5.0, is the easiest way to handle the most likely case of a brand new cluster with nodes coming up at the same time. 0.5.0 should be released within the next week.
