### ISSUE TITLE
Auto cluster with EC2 Auto-scale up/down

### ISSUE THREAD

**Issue by Giri-Chintala** [aweber/rabbitmq-autocluster#44]
Hi, 
i am using auto cluster plugin with EC2 Auto Scale Group (ASG).

encountered clustering issues in a scenario, a EC2 instance was member of a cluster, but it was terminated and re-launched (as part of scale-up/down) with same host name and trying to join same cluster.

Our EC2 hostnames are derived from IP address and ASG picks available ip-address with in the subnet. so it is possible to re-launch a host with same name which was previously terminated and member of same cluster. 

Here is my scenario. 

1. Started with ASG size 1, EC2 launched ip-204-71-137 and rabbit started successfully 
2. Updated ASG size to 3, EC2 launched two more instances ip-204-71-139, ip-204-71-155, they both joined cluster with ip-204-71-137.
3. Updated ASG size bak to 1, EC2 terminated ip-204-71-139 and ip-204-71-155. so one node ip-204-71-137 is left in cluster .
4. Updated EC2 ASG size to 3, EC2 launched two more instances ip-204-71-139 , ip-204-71-156.  EC2 recycled ip-204-71-139 as it was previously terminated.   ip-204-71-156 joined rabbit cluster(ip-204-71-137) without any issues, but auto-cluster plugin recognized that ip-204-71-139 is Already member of cluster ['rabbit@ip-204-71-137','rabbit@ip-204-71-156', 'rabbit@ip-204-71-155','rabbit@ip-204-71-139'] and tried to start rabbit on 137 and failed.

Here is the full log on ip-204-71-137 from second launch ..

=INFO REPORT==== 3-Feb-2016::20:48:20 ===
autocluster: Registering node with consul

=INFO REPORT==== 3-Feb-2016::20:48:20 ===
Resetting Rabbit

=INFO REPORT==== 3-Feb-2016::20:48:22 ===
**Already member of cluster: ['rabbit@ip-204-71-137','rabbit@ip-204-71-156',
                            'rabbit@ip-204-71-155','rabbit@ip-204-71-139']**

=INFO REPORT==== 3-Feb-2016::20:48:25 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 3-Feb-2016::20:48:25 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 3-Feb-2016::20:48:25 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 3-Feb-2016::20:48:25 ===
started TCP Listener on [::]:5671

=INFO REPORT==== 3-Feb-2016::20:48:26 ===
started SSL Listener on [::]:5672

=INFO REPORT==== 3-Feb-2016::20:48:26 ===
autocluster: Starting Consul Health Check TTL Timer

=INFO REPORT==== 3-Feb-2016::20:48:28 ===
Management plugin started. Port: 15672

=INFO REPORT==== 3-Feb-2016::20:48:28 ===
stopped SSL Listener on [::]:5672

=INFO REPORT==== 3-Feb-2016::20:48:28 ===
stopped TCP Listener on [::]:5671

=INFO REPORT==== 3-Feb-2016::20:48:29 ===
Error description:
   {could_not_start,rabbitmq_management,
       {{shutdown,
            {failed_to_start_child,rabbit_mgmt_sup,
                {'EXIT',
                    {{shutdown,
                         [{{already_started,<10869.1317.0>},
                           {child,undefined,rabbit_mgmt_db,
                               {rabbit_mgmt_db,start_link,[]},
                               permanent,4294967295,worker,
                               [rabbit_mgmt_db]}}]},
                     {gen_server2,call,
                         [<0.569.0>,{init,<0.567.0>},infinity]}}}}},
        {rabbit_mgmt_app,start,[normal,[]]}}}

**Comment by efii** [comment]
At least for the case where the instance is shut down cleanly, as opposed to crashing, the node can disconnect from the cluster with rabbitmqctl reset during the shutdown process.

**Comment by Giri-Chintala** [comment]
I think it is bug on RabbitMQ side

Clean shutdown node is able to join the cluster once it is restarted. 

But in the sceraio when EC2 instance is terminated, re-launched with same host name with fresh installation and re-join cluster, rabbitmqctl join_cluster thinks that node is already member of the cluster (based on the exiting cluster status ), without considering the fact that re-joining node has no idea about existing cluster node and starts node normally without actually join cluster.

I think RabbitMQ should be intelligent enough to join exiting cluster nodes and re-joining node as re-joining node explicitly invoking join-cluster. 

I opened a discussion on this in rabbitmq google groups

https://groups.google.com/forum/m/#!topic/rabbitmq-users/-1gw9ZYHGyw






I think rabbit

**Comment by efii** [comment]
I believe this is actually a "feature" of rabbitmq, not a bug, but I also believe that rabbitmq (or autocluster) should have a config option that turns off this check and allows nodes to join as long as an active node of the same name isn't currently running in the cluster,

With OpsWorks, at least, you can add a recipe that's run prior to termination that removes the node from the cluster before shutting down.  Like I said, this doesn't solve the issue of a crashed node; it only helps those that are shut down cleanly.

**Comment by Giri-Chintala** [comment]
autocluster is actually doing its job right, 

1. register the node with consul, 
2. application:stop(rabbit),
3. mnesia:stop(),
4. rabbit_mnesia:reset(),
5. rabbit_mnesia:join_cluster(lists:nth(1, Alive),
6.  mnesia:start(),
7.  rabbit:start(),


but on `rabbit_mnesia:join_cluster(lists:nth(1, Alive)` call, RabbitMQ code [rabbit_mnesia.erl line number  207](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_mnesia.erl)  thinks that re-joining node is Already member of cluster, starts node without actually joining cluster.

=INFO REPORT==== 3-Feb-2016::20:48:20 ===
**autocluster: Registering node with consul**

=INFO REPORT==== 3-Feb-2016::20:48:20 ===
Resetting Rabbit

**=INFO REPORT==== 3-Feb-2016::20:48:22 ===
Already member of cluster: ['rabbit@ip-204-71-137','rabbit@ip-204-71-156',
'rabbit@ip-204-71-155','rabbit@ip-204-71-139']**

**Comment by Giri-Chintala** [comment]
reason why i am thinking it is rabbit bug is, `rabbit_mnesia:join_cluster()` is not actually joining node with cluster and not even throwing error.

**Comment by efii** [comment]
I think you're right -- autocluster performs a reset(), which calls reset_gracefully(), which calls leave_cluster().  This normally works if rabbitmq is up and running and already joined to the cluster (the leave_cluster() call propagates to the other nodes), but doesn't work if it can't start up (management plugin crashing on startup) or it isn't already joined to the cluster (which a fresh node isn't while it's booting but before calling a join_cluster).  This appears to be a "chicken-and-egg" situation where either reset or join_cluster needs to change to behave a little differently at startup (vs. when it's called from rabbitmqctl).

**Comment by michaelklishin** [comment]
Thanks for your findings. We'd consider adding a new function that does what this plugin needs for `3.6.x`. For `3.7.0`, we hope to have the same functionality in the core.

**Comment by gmr** [comment]
I released 0.5.0 today, which adds the support to remove dead nodes from the cluster.

**Comment by devopsberlin** [comment]
@gmr , I am using `RabbitMQ 3.6.6 on Erlang 19.1.3 and autocluster 0.6.1 plugin` and it seems that when a node goes down, RabbitMQ does not remove it from the replication list automatically, do you know maybe why ?
