### ISSUE TITLE
Release `CONSUL_SERVER_ADDRESS to support non-local consul agents` fix

### ISSUE THREAD

**Issue by AlexeyRaga** [aweber/rabbitmq-autocluster#45]
I see that the issue with non-local consul agents has been resolved, could you please make a release containing this fix?

**Comment by KrzysztofZalasa** [comment]
+1

Without this change I cannot use your great plugin in docker, which is current standard. Release for branch 3.5 of RabittMQ will be good enough.

**Comment by gmr** [comment]
0.5.0 will be released within a week.
