### ISSUE TITLE
autoclustering not working at all when using long names

### ISSUE THREAD

**Issue by joeblackwaslike** [aweber/rabbitmq-autocluster#50]
I have no problems with autoclustering using erlang short names, but if i enable long names i get an error message when the plugin tries to join the other node using only a shortname.

With the logging level for autocluster turned all the way up I see the following in the log:

=ERROR REPORT==== 24-Feb-2016::05:54:57 ===
** System running to use fully qualified hostnames **
** Hostname rabbitmqalpha is illegal **

=ERROR REPORT==== 24-Feb-2016::05:54:57 ===
autocluster: Can not communicate with cluster nodes: [rabbit@rabbitmqalpha]

I looked through your recent commits and noticed there were some fixes made for consul. Did they address any of these issues?  I attempted to build the plugin from source but it failed miserably for both the umbrella and this project.  Do you maybe even have a builder docker that builds the plugin?  in the long term we'd really prefer to use erlang long names in all our nodes. 

Thanks!

**Comment by TMiNus** [comment]
I had to deal with this today, the workaround that I found was defining **RABBITMQ_USE_LONGNAME=true** as an **environment variable**. For some reason if you define **USE_LONGNAME=true** in **rabbit-env.conf** the plugin doesnt work. Dunno why, some clarification will be nice

**Comment by gmr** [comment]
It currently doesn't support the truncated environment variables from the rabbit-env.conf file (and does not advertise doing so). I'll open a ticket to addrabbit-env.conf support to a future release.
