### ISSUE TITLE
Clustering fails when using dns backend

### ISSUE THREAD

**Issue by bartekrutkowski** [aweber/rabbitmq-autocluster#51]
Using manually compiled plugin from latest sources, with rabbitmq-server-3.6.0 I can't get the autoclustering to work at all. I've tried number of configurations, with the latest being like that:

```
{autocluster,
  [
   {backend, dns},
   {autocluster_host, "cluster.example.com"}
  ]}
```

and the only output I am getting from the plugin (also, no matter what debug level is being set up) is that:

```
=ERROR REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Error resolving host by address: {error,nxdomain}

=ERROR REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Error resolving host by address: {error,nxdomain}

=INFO REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Registering node with dns

=INFO REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Registered node

=INFO REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Node is only node in the cluster

=INFO REPORT==== 25-Feb-2016::15:47:09 ===
autocluster: Node appears to be the first in the cluster
```

I also tried using `longname` and `RABBITMQ_USE_LONGNAME`, using precompiled 0.4.1 plugin version, but without any luck. Is there any way to see what exactly autocluster is failing to resolve?

**Comment by gmr** [comment]
The branch is not stable, has a bunch of PRs that break things and I've only got the base compilation working. I'll be spending more time with it soon.

**Comment by bartekrutkowski** [comment]
Can you suggest any particular tag/version/branch that has dns backend working?

**Comment by rschwiebert** [comment]
Doh, wish I could have found this earlier. Any ETA on when things might be better? Or a link to a build in which dns works?

**Comment by gmr** [comment]
In testing, nothing appears to be seriously broken here. Are you sure that DNS resolution is properly able to find the A-Record round-robin values?

``autocluster: Error resolving host by address: {error,nxdomain}``

**Comment by wyardley** [comment]
I'm having problems as well, 

```
% Additional config
  {autocluster, [
        {backend, dns},
        {autocluster_host, "foo.example.net"},
        {autocluster_log_level, "debug"}]}
].
```
I've also tried using short and long names (and adding / removing trailing dot) for autocluster_host, and adding
```
        {longname, true},
```
(since the hostnames are in different subdomains)
and 
```
        {cluster_name="rabbit"}
```
However, even with this, cluster status shows:
```
 {cluster_name,<<"rabbit@rabbitmq-i-eb32ba44.example.net">>},
``` 
What will happen if cluster_name is not explicitly set, will it just default to the hostname of the first node that adds itself?

Forward and reverse DNS should be correct for all nodes, and the logging gets farther than for the OP:

```
=INFO REPORT==== 28-Jul-2016::21:28:44 ===
autocluster: Using DNS backend

=INFO REPORT==== 28-Jul-2016::21:28:44 ===
autocluster: Delaying startup for 1134ms.

=INFO REPORT==== 28-Jul-2016::21:28:45 ===
autocluster: Starting dns registration.

=INFO REPORT==== 28-Jul-2016::21:28:45 ===
autocluster: Registering node with dns.

=INFO REPORT==== 28-Jul-2016::21:28:45 ===
autocluster: Registered node with dns.

=INFO REPORT==== 28-Jul-2016::21:28:45 ===
autocluster: Discovered []

=INFO REPORT==== 28-Jul-2016::21:28:45 ===
autocluster: No other nodes are registed with the backend.

```

```
;; QUESTION SECTION:
;rabbitmq.foo.example.net.	IN	A

;; ANSWER SECTION:
rabbitmq.foo.example.net. 58	IN	A	10.4.1.91
rabbitmq.foo.example.net. 58	IN	A	10.4.3.227
$ dig -x 10.4.1.91 +short
rabbitmq-i-ad1239fd.az-a.foo.example.net.
$ dig -x 10.4.3.227 +short
rabbitmq-i-eb35ba3a.az-b.foo.example.net.
```

**Comment by ricardclau** [comment]
I got bitten by this... in my case it was not the A-record round-robin values but the reverse lookup on each one of the ip addresses in that round-robin A-record

Some info was added at https://github.com/aweber/rabbitmq-autocluster/issues/84 and I will send a PR this week with better docs and troubleshooting for the DNS backend!

**Comment by ricardclau** [comment]
Just for reference, I added some troubleshooting for DNS backend at https://github.com/aweber/rabbitmq-autocluster/wiki/DNS%20Configuration

Hope that can help!

**Comment by gmr** [comment]
That's great, thanks!

**Comment by Oloremo** [comment]
Hello, I have the exact error:

```
=INFO REPORT==== 8-Sep-2016::13:31:33 ===
autocluster: Starting dns registration.

=ERROR REPORT==== 8-Sep-2016::13:31:33 ===
autocluster: Error resolving host by address: {error,nxdomain}

=ERROR REPORT==== 8-Sep-2016::13:31:33 ===
autocluster: Error resolving host by address: {error,nxdomain}

=ERROR REPORT==== 8-Sep-2016::13:31:33 ===
autocluster: Error resolving host by address: {error,nxdomain}

=INFO REPORT==== 8-Sep-2016::13:31:33 ===
autocluster: Registering node with dns.
```
And I checked what resolving is working in my case:

```
rabbitmq@rabbitmq-4bitu:/$ erl
Eshell V7.3.1  (abort with ^G)
1> inet_res:lookup("rabbitmq.ccp.svc.cluster.local", in, a).
[{10,233,73,196},{10,233,83,79},{10,233,86,82}]
```

autocluster config:

```
  ,{autocluster, [
      {dummy_param_without_comma, true}
     ,{backend, dns}
     ,{autocluster_host, "rabbitmq.ccp.svc.cluster.local"}
   ]}
```

Using the lates commit in master. Any ideas?

Suggestion: 
Make this log string a bit more verbose:
`autocluster: Error resolving host by address: {error,nxdomain}`

**Comment by wyardley** [comment]
@Oloremo: did you check the reverse records?

**Comment by Oloremo** [comment]
@wyardley This IP addrs doesn't have a PTR records. Does it mandatory for DNS plugin? I can't see a reason why it should. We want to use ip addrs as a node names in this cluster, we dont really care about PTR.

**Comment by wyardley** [comment]
@Oloremo: did you get it working yet? I'm not affiliated with this plugin, just another user (and had some similar problems figuring out what was going on when things weren't working).

But if you notice the troubleshooting link above, as well as @ricardclau's comment, it does mention having the reverse records (having them in /etc/hosts may suffice).

**Comment by Oloremo** [comment]
@wyardley Thaks for your concern. :-) 

No, I gave up with dns discovery for now and testing etcd plugin. /etc/hosts is not a good solution for k8s cluster and kube-dns only creating PTR records for PetSets, which I dont want to use right now. Sadly, etcd plugin has it's own issues aswell. :(

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
