### ISSUE TITLE
ETCD has a slash in the hostnames?

### ISSUE THREAD

**Issue by mattwilliamson** [aweber/rabbitmq-autocluster#52]
When trying to cluster with ETCD, it looks like the hostnames have a / stuck into the front.

```
2/29/2016 2:59:56 PM=INFO REPORT==== 29-Feb-2016::19:59:56 ===
2/29/2016 2:59:56 PMautocluster: Node is only node in the cluster
2/29/2016 2:59:56 PM
2/29/2016 2:59:56 PM=ERROR REPORT==== 29-Feb-2016::19:59:56 ===
2/29/2016 2:59:56 PMautocluster: Can not communicate with cluster nodes: ['rabbit@/inflight-shard-1_rabbitmq_1',
2/29/2016 2:59:56 PM                                                      'rabbit@/inflight-shard-1_rabbitmq_2',
2/29/2016 2:59:56 PM                                                      'rabbit@/inflight-shard-1_rabbitmq_3']
```

**Comment by fiksn** [comment]
I can confirm the issue.

> 
=ERROR REPORT==== 3-Mar-2016::14:56:15 ===
autocluster: Can not communicate with cluster nodes: ['rabbit@/XYZ']

I did
``
rabbitmqctl eval "autocluster_etcd:nodelist()." 
``
and get 
``
{ok,['rabbit@/XYZ','rabbit@/ABC']} 
``
After some investigation I found the problem to be in https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_etcd.erl#L152, there should be length(Path)+1. 

Perhaps I should submit a pull request, but I am not really familiar with Erlang, so this will take a bit before I build this and run the unit tests.

**Comment by fiksn** [comment]
Perhaps it should also be worth mentioning that I was running with etcd_prefix = "rabbitmq", cluster_name = "rmq-settlement" and thus
``rabbitmqctl eval "string:concat(autocluster_httpc:build_path(lists:sublist(autocluster_etcd:base_path(), 3, 2)), \"/\")."
``
was 
``"/rabbitmq/rmq-settlement/"
``

Perhaps with default cluster_name it is different.

**Comment by fiksn** [comment]
Infact the current code as of today is correct, so ignore my previous comment about +1. 
Whole thing was fixed in https://github.com/aweber/rabbitmq-autocluster/commit/5b46c371cc4bd9be493caef7b790152ab0829785 but 0.4.1 release does not have that yet.

**Comment by joeblackwaslike** [comment]
i'm having the same issue, and am unfamiliar with building rabbitmq plugins.  I also tried to follow the build instructions but it wouldn't work for me.  

If anyone who has built the fixed version can link me i'll owe you big time! 

Thanks

**Comment by pbecotte** [comment]
I cut a 0.5 release on the Bamx fork of this repo that has this fixed.

**Comment by gmr** [comment]
0.5.0 will drop within the next week.
