### ISSUE TITLE
Support multi consul servers in a consul cluster

### ISSUE THREAD

**Issue by dunty** [aweber/rabbitmq-autocluster#55]
If I have three consul servers in a cluster, one failed, others can continuely work.  Right now, only one server can configed in ```consul_host```,  but if that server is done, how to switch to other servers?

**Comment by gregdurham** [comment]
The recommended way to do this is to use a consul agent locally on the server running rabbitmq. This will allow the agent to keep track of cluster membership, and a single consul server for rabbitmq-autocluster to connect to, i.e. localhost.

**Comment by dunty** [comment]
@gregdurham, thanks for your patiently answer. I'll try this.
