### ISSUE TITLE
The NODENAME is fixed on 'rabbit', can not support other value

### ISSUE THREAD

**Issue by dunty** [aweber/rabbitmq-autocluster#56]
In my rabbitmq-env.conf, I can change the NODENAME to other value, like:
```
#Rename the node
NODENAME=mq
MNESIA_BASE=/home/rabbitmq/mq-data
LOG_BASE=/home/rabbitmq/rabbitmq_server-3.6.1/log
```
every server is configed as the same NODENAME.
but, when I start the rabbitmq servers, they are not clustered, and in log:
```
=ERROR REPORT==== 10-Mar-2016::17:11:02 ===
autocluster: Can not communicate with cluster nodes: [rabbit@xxxxxxxxx]
```

so, the NODENAME of servers in the cluster, should not change to other value?

**Comment by gregdurham** [comment]
Hey @dunty I think it is hardcoded here, this would explain why there is no way to currently override that value: 
https://github.com/aweber/rabbitmq-autocluster/blob/b3472595e01800577d6f3c45ffa992000e579785/src/autocluster_util.erl#L61-L71

```erlang
node_name(Value) ->
  Host = case autocluster_config:get(longname) of
    true  -> as_string(Value);
    false ->
      Parts = string:tokens(as_string(Value), "."),
      case length(Parts) of
        1 -> as_string(Value);
        _ -> as_string(lists:nth(1, Parts))
      end
  end,
  list_to_atom(string:join(["rabbit", Host], "@")).
```

**Comment by gmr** [comment]
This will be supported in 0.5.0 which should drop within the next week.
