### ISSUE TITLE
Nodes are not leaving the cluster

### ISSUE THREAD

**Issue by madAndroid** [aweber/rabbitmq-autocluster#57]
Hi, I've got an autoscaling group of 3 instances, and when I kill off a node, the killed nodes are not being removed from the cluster - is this normal operation?

The output of `rabbitmqctl cluster_status`
```
Cluster status of node 'rabbit@user-stg-messaging-ia9e19d21' ...
[{nodes,[{disc,['rabbit@user-stg-messaging-i26f37cac',
                'rabbit@user-stg-messaging-i40700fc8',
                'rabbit@user-stg-messaging-ia9e19d21',
                'rabbit@user-stg-messaging-ib12aa53b',
                'rabbit@user-stg-messaging-ieba5da63']}]},
 {running_nodes,['rabbit@user-stg-messaging-ib12aa53b',
                 'rabbit@user-stg-messaging-ieba5da63',
                 'rabbit@user-stg-messaging-ia9e19d21']},
 {cluster_name,<<"rabbit@user-stg-messaging-i40700fc8">>},
 {partitions,[]}]
```
That's after two nodes have been killed off - I'd expected them to have been removed from the nodes list, but they don't appear to be getting removed.

**Comment by madAndroid** [comment]
Some more details:
```
[root@user-stg-messaging-ib12aa53b ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@user-stg-messaging-ib12aa53b ~]# rpm -qa | grep rabbit
rabbitmq-server-3.3.5-17.el7.noarch
```
Running the latest version of autocluster: `0.4.1`

**Comment by gmr** [comment]
This is intentional. The current version does not remove nodes, you need to do this manually. I did not feel comfortable making such destructive action without some serious thought about it.

**Comment by madAndroid** [comment]
@gmr - that makes sense - thanks for explaining :)
Another question, I hope you don't mind .. is there anyway to set the name of the cluster to anything other than the first node that starts the cluster? ie, is there a way to set the cluster name to a specific name, so that it's easier to identify? Seems this is probably a rabbitmq specific clustering behaviour, but it would be great if we were able to override this somehow
