### ISSUE TITLE
Consul: use an other node/service address

### ISSUE THREAD

**Issue by Mika56** [aweber/rabbitmq-autocluster#62]
As stated in my previous ticket, I'm working in an environment that uses DHCP but has no dynamic DNS. However, our DNS servers are configured to redirect consul. requests to Consul.

I'm trying to make this plugin register my hosts as `hostname.node.consul` instead of `hostname` (with no FQDN), but I cannot get it to work.
So far, I've tried setting my /etc/rabbitmq/rabbitmq-env.conf as follow:

``` bash
USE_LONGNAME=true
NODENAME="rabbit@`env hostname`.node.consul"
RABBITMQ_NODENAME=$NODENAME
LONGNAME=$NODENAME
RABBITMQ_NODENAME=$NODENAME
```

While RabbitMQ accepts the NODENAME variable (my log file has changed name and the beginning says the node name is `rabbit@something.node.consul`), rabbitmq-autocluster seems to still register the service as `something`, instead of `something.node.consul`. I've tried to read the source code but this is the first time I've ever read Erlang and this was not a success :stuck_out_tongue: 

Anyway, here's how the service is registered:

``` javascript
[
    {
        Node: {
            Node: "rabbitmq-698a01f",
            Address: "172.16.4.50",
            TaggedAddresses: {
                wan: "172.16.4.50"
            },
            CreateIndex: 54874,
            ModifyIndex: 168565
        },
        Service: {
            ID: "rabbitmq",
            Service: "rabbitmq",
            Tags: [
                "dc1"
            ],
            Address: "",
            Port: 5672,
            EnableTagOverride: false,
            CreateIndex: 168565,
            ModifyIndex: 168565
        },
        Checks: [
            {
                Node: "rabbitmq-698a01f",
                CheckID: "serfHealth",
                Name: "Serf Health Status",
                Status: "passing",
                Notes: "",
                Output: "Agent alive and reachable",
                ServiceID: "",
                ServiceName: "",
                CreateIndex: 54874,
                ModifyIndex: 165990
            },
            {
                Node: "rabbitmq-698a01f",
                CheckID: "service:rabbitmq",
                Name: "Service 'rabbitmq' check",
                Status: "passing",
                Notes: "RabbitMQ Auto-Cluster Plugin TTL Check",
                Output: "",
                ServiceID: "rabbitmq",
                ServiceName: "rabbitmq",
                CreateIndex: 168565,
                ModifyIndex: 168565
            }
        ]
    }
]
```

What property does rabbitmq-autocluster reports to RabbitMQ? Is it Node.Node or can it report Service.Address? If so, how can I change what Service.Address is reported to Consul? I need it to be deducted from the machine's hostname, as we are building virtual machine templates that are to be automatically deployed.

**Comment by gmr** [comment]
Few things:
- rabbitmq-env.conf is not currently supported for autocluster. I have a change that may change that for the next release.
- Have a look at [Consul Configuration](https://github.com/aweber/rabbitmq-autocluster/wiki/Consul%20Configuration) and let me know what I can do to make it more clear on that.  I believe what you're looking for is the *Service Address* or *Service Auto Address* configuration variables. As environment variables those are ``CONSUL_SVC_ADDR`` or ``CONSUL_SVC_ADDR_AUTO``.

**Comment by gmr** [comment]
You'll want to give 0.6.0 a try, I think it should address your issues.

**Comment by Mika56** [comment]
Hi,

Thank you for working with me on this.
I've tried v0.6.0 and I sorta got it to work!

It seems you have a bug (or at least I think), because the `USE_LONGNAME` environment variable is not read properly by Autocluster. Even when set to true, Autocluster will cut the name and take the first part of the FQDN.
However, there is an undocumented setting that can be set, `longname`, that, when set to true, will force Autocluster to use long names.

Sadly, I still need to set the `CONSUL_SVC_ADDR` environment variable, and it seems it is not read properly either. I don't think I can achieve what I want by using the `consul_svc_addr` variable in the config file, as I need it to derive the hostname from the host.

**Comment by Mika56** [comment]
Hey,

Any chance you were able to take a look?

**Comment by gmr** [comment]
I've not, but I'm curious as to why you think it's not reading the config properly. There is 100% test coverage of part of the code and I've checked it previously.  Perhaps the environment variables are not being passed down to your RabbitMQ instance? One way you could tell for sure is to connect via erlang into your RabbitMQ server that's not seeing the variables and try and fetch them yourself. For example, connect in via:

```bash
erl -sname test -remsh rabbit@NODENAME
```

Then run:

```erlang
Erlang/OTP 17 [erts-6.4.1] [source-381fb6c] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.4.1  (abort with ^G)
(rabbit@rabbit1)1>  os:getenv("RABBITMQ_USE_LONGNAME").
"true"
(rabbit@rabbit1)2> autocluster_config:get(longname).
true
(rabbit@rabbit1)3> os:getenv("CONSUL_SVC_ADDR").
"192.168.1.1"
(rabbit@rabbit1)4> autocluster_config:get(consul_svc_addr).
"192.168.1.1"
```

**Comment by ex3ndr** [comment]
This doesn't work for me neither. Also sends short name instead of long name.

**Comment by michaelklishin** [comment]
The library gets the host name via [int:gethostname/0](https://github.com/aweber/rabbitmq-autocluster/blob/a8271e8d71b38dd917957aee0f4bd35d055f43f6/src/autocluster_util.erl#L162).

So if you have a long name configured, should the plugin extract hostname from it or report what `inet:gethostname/0` returns? I don't have an answer, the former seems less confusing to me but I can certainly see how the opposite view can make a lot of sense to some.

**Comment by dcorbacho** [comment]
@Mika56 @ex3ndr The use of long names and service addresses has been verified against `master`, please see the logs below.
```
$ RABBITMQ_NODENAME=rabbit@this.node.consul USE_LONGNAME=true CONSUL_SVC_ADDR=this.node.consul AUTOCLUSTER_TYPE=consul  CONSUL_HOST=localhost gmake run-broker
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:8:8] [async-threads:128] [hipe] [kernel-poll:true]

Eshell V8.0  (abort with ^G)
(rabbit@this.node.consul)1>
              RabbitMQ 3.6.7.rc2+16.gaa28020. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /var/folders/34/x13f96mn2m7d6z683pkb8bhm0000gq/T/rabbitmq-test-instances/rabbit@this.node.consul/log/rabbit@this.node.consul.log
  ######  ##        /var/folders/34/x13f96mn2m7d6z683pkb8bhm0000gq/T/rabbitmq-test-instances/rabbit@this.node.consul/log/rabbit@this.node.consul-sasl.log
  ##########
              Starting broker...
 completed with 3 plugins.

(rabbit@this.node.consul)1>
```

<img width="806" alt="screen shot 2017-03-17 at 2 45 44 pm" src="https://cloud.githubusercontent.com/assets/646577/24048344/765a51ce-0b20-11e7-8290-6a652782fe8c.png">

The following PR in the RabbitMQ fork allows to use longnames from nodenames instead of using `inets`, with the env variable `CONSUL_SVC_ADDR_NODENAME=true`:
https://github.com/rabbitmq/rabbitmq-autocluster/pull/4

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
