### ISSUE TITLE
Add support for pluggable backends

### ISSUE THREAD

**Issue by gmr** [aweber/rabbitmq-autocluster#63]
One of the lessons learned in adding AWS support was that I could either create my own AWS library and include it in the plugin or depend on an external library. I ended up doing both which is a different story, but not the point.

With each additional protocol that is required which has extra tooling, such as Zookeeper (#23), we will have to ship the plugin with a support library for that protocol. In the case of Zookeeper, I found a pure Erlang client (https://github.com/huaban/erlzk), that I could hopefully use. However, I do not want that to be a dependency for the base plugin to work.

To achieve multiple protocol support and to make the pathway for eventual integration with RabbitMQ easier, the plugin should be updated to be agnostic to the protocol used for service discovery/management.

One could make the case that all of the backends should be broken out into their own plugin that implements the ``autocluster_backend`` behavior.

**Comment by michaelklishin** [comment]
FTR, team RabbitMQ is certainly interested in integrating the core of this plugin into a future RabbitMQ version. RabbitMQ has many pluggable things and we don't do anything sophisticated there: just a behaviour (interface) and implementation modules which are specified in configuration by the user.

**Comment by binarin** [comment]
So are you OK with plugin for every non-standalone backend  approach? I can do this, it will look like this:
- New plugin `autocluster_aws`  where existing ` autocluster_aws.erl` will be moved.
- New top-level repository `autocluster-release`, which will depend both on existing `autocluster` and on the new `autocluster_aws`.
