### ISSUE TITLE
AWS discovery fails

### ISSUE THREAD

**Issue by plorent** [aweber/rabbitmq-autocluster#65]
I'm running an ECS cluster with two tagged instances and both instances are running the Docker container with configuration (excerpt):

`{autocluster, [
    {backend, aws},
    {aws_ec2_tags, [{"region", "eu-west-1"}, {"service", "rabbitmq"}]},
    {aws_ec2_region, "eu-west-1"},
    {aws_access_key, "THEKEY"},
    {aws_secret_key, "THESECRETKEY"}
  ]}`

The error report I'm getting in the logs:
=ERROR REPORT==== 4-Jun-2016::12:39:25 ===
autocluster: Could not fetch node list from autocluster_aws: no_configured_tags.

When trying the autoscale group option, the error is the same. I have applied the appropriate policy.

Any ideas what I'm doing wrong?

**Comment by gmr** [comment]
I have a working CloudFormation template @ https://github.com/gmr/alpine-rabbitmq-autocluster that you may want to check out.

Without the full startup logs, it's hard to diagnose exactly what's up.  If you're able, try and run with debug logging enabled and then share the logs here, scrubbing any sensitive data. This can be achieved either by adjusting the log level in the rabbitmq configuration or by setting the AUTOCLUSTER_LOG_LEVEL=debug environment variable.

**Comment by plorent** [comment]
Great, the clustering mechanism works as expected using your CloudFormation template. Thanks for this great plugin! It makes life a lot simpler :-)

**Comment by rumenvasilev** [comment]
Same issue reported here: https://github.com/aweber/rabbitmq-autocluster/issues/75
And the fix, pending merge: https://github.com/aweber/rabbitmq-autocluster/pull/90

**Comment by karambolishe** [comment]
anybody can help me understand what is my problem... I try configured autocluster by tags and I already broke my mind.

Rabbit tells me about tags isn't configured...
 _=ERROR REPORT==== 18-Nov-2016::17:13:11 ===
autocluster: Could not fetch node list from autocluster_aws: no_configured_tags._

## _version packages:_
rabbitmq-server 3.3.5-26.el7
erlang R16B-03.17.el7

## _My rabbit config:_
`[
  {rabbit,
     [
       {log_levels, [{autocluster, debug},
                    {connection, debug},
                    {connection, error},
                    {channel, warning},
                    {federation, info},
                    {mirroring, info},
                    {shovel, info}]},
       {vm_memory_high_watermark, 0.9},
       {disk_free_limit, 4000000000}
     ]
  },
  {autocluster,
     [
        {backend, aws},
        {aws_ec2_tags, [{"service", "rabbitmq"}]},
        {aws_ec2_region, "eu-central-1b"},
        {aws_access_key, "value"},
        {aws_secret_key, "value"}
    ]
  }
].`

## _List of my plugins that enabled_

[root@ip ~]# rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@ip - status not shown]
 |/
[  ] amqp_client                       3.6.5
[E ] autocluster                       0.6.1
[  ] cowboy                            1.0.3
[  ] cowlib                            1.0.1
[  ] mochiweb                          2.13.1
[  ] rabbitmq_amqp1_0                  3.6.5
[  ] rabbitmq_auth_backend_ldap        3.6.5
[  ] rabbitmq_auth_mechanism_ssl       3.6.5
[e ] rabbitmq_aws                      0.1.2
[  ] rabbitmq_consistent_hash_exchange 3.6.5
[  ] rabbitmq_event_exchange           3.6.5
[  ] rabbitmq_federation               3.6.5
[  ] rabbitmq_federation_management    3.6.5
[  ] rabbitmq_jms_topic_exchange       3.6.5
[  ] rabbitmq_management               3.6.5
[  ] rabbitmq_management_agent         3.6.5
[  ] rabbitmq_management_visualiser    3.6.5
[  ] rabbitmq_mqtt                     3.6.5
[  ] rabbitmq_recent_history_exchange  1.2.1
[  ] rabbitmq_sharding                 0.1.0
[  ] rabbitmq_shovel                   3.6.5
[  ] rabbitmq_shovel_management        3.6.5
[  ] rabbitmq_stomp                    3.6.5
[  ] rabbitmq_top                      3.6.5
[  ] rabbitmq_tracing                  3.6.5
[  ] rabbitmq_trust_store              3.6.5
[  ] rabbitmq_web_dispatch             3.6.5
[  ] rabbitmq_web_stomp                3.6.5
[  ] rabbitmq_web_stomp_examples       3.6.5
[  ] sockjs                            0.3.4
[  ] webmachine                        1.10.3


## _IAM roles that has been attached to rabbit instances_
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingInstances",
                "ec2:DescribeInstances"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
`}


## _My log:_

=INFO REPORT==== 18-Nov-2016::17:13:05 ===
Starting RabbitMQ 3.6.5 on Erlang 19.1
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/


=INFO REPORT==== 18-Nov-2016::17:13:05 ===
node           : rabbit@ip
home dir       : /home/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : “value”
log            : /var/log/rabbitmq/rabbit@ip.log
sasl log       : /var/log/rabbitmq/rabbit@ip-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@ip-


=INFO REPORT==== 18-Nov-2016::17:13:09 ===
autocluster: Delaying startup for 2665ms.


=INFO REPORT==== 18-Nov-2016::17:13:11 ===
autocluster: Starting aws registration.


=ERROR REPORT==== 18-Nov-2016::17:13:11 ===
autocluster: Could not fetch node list from autocluster_aws: no_configured_tags.


=INFO REPORT==== 18-Nov-2016::17:13:11 ===
Memory limit set to 14067MB of 15630MB total.


=INFO REPORT==== 18-Nov-2016::17:13:11 ===
Disk free limit set to 4000MB


=INFO REPORT==== 18-Nov-2016::17:13:11 ===
Limiting to approx 299900 file handles (269908 sockets)


=INFO REPORT==== 18-Nov-2016::17:13:11 ===
FHC read buffering:  OFF
FHC write buffering: ON


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@ip is empty. Initialising from scratch...


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Priority queues enabled, real BQ is rabbit_variable_queue


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Adding vhost '/'


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Creating user 'guest'


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Setting user tags for user 'guest' to [administrator]


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index


=WARNING REPORT==== 18-Nov-2016::17:13:12 ===
msg_store_persistent: rebuilding indices from scratch


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
started TCP Listener on [::]:5672


=INFO REPORT==== 18-Nov-2016::17:13:12 ===
Server startup complete; 2 plugins started.
 * autocluster
 * rabbitmq_aws

If somebody have a little time to help me I would be very grateful.
Thank for advance

**Comment by michaelklishin** [comment]
@karambolishe you use `0.6.1` which was released in June and does not include #90.

**Comment by karambolishe** [comment]
Thank you for very quick response. But would you fix me if I don't correct understood?

1. For use feature "autocluster+tags", I need build from last source code(last Commits on Oct 28, 2016). 
2. make && make dist.
3. To take built plugins (autocluster-0.6.1.ez, autocluster_aws-0.0.1.ez, rabbit_common.ez, rabbitmq_aws-0.1.3.ez) and enable by rabbitmq-plugins enable autocluster. 
4. Change config like those that I mention in previously comment.

**Comment by michaelklishin** [comment]
All `.ez` files except for `rabbit_common.ez` must replace the plugin archives you already have in the plugins directory. There is no need to re-enable the plugin but you do need to restart your nodes.

**Comment by karambolishe** [comment]
I performed your tips and now my log contents :  

> =INFO REPORT==== 20-Nov-2016::22:53:51 ===
> autocluster: Delaying startup for 388ms.
> 
> =INFO REPORT==== 20-Nov-2016::22:53:51 ===
> autocluster: Starting aws registration.
> 
> =ERROR REPORT==== 20-Nov-2016::22:53:51 ===
> ** Generic server rabbitmq_aws terminating
> ** Last message in was {request,"ec2",get,[],
>                                 "/?Action=DescribeInstances&Filter.1.Name=tag%3Aregion&Filter.1.Value.1=eu-central-1b&Filter.2.Name=tag%3Aservice&Filter.2.Value.1=rabbitmq&Version=2015-10-01",
>                                 [],[],undefined}
> ** When Server state == {state,"my_cookies",
>                                "my_aws_credentials",
>                                undefined,undefined,"eu-central-1b",undefined}
> ** Reason for termination ==
> ** {function_clause,
>        [{rabbitmq_aws,format_response,
>             [{error,
>                  {failed_connect,
>                      [{to_address,{"ec2.eu-central-1b.amazonaws.com",443}},
>                       {inet,[inet],nxdomain}]}}],
>             [{file,"src/rabbitmq_aws.erl"},{line,229}]},
>         {rabbitmq_aws,perform_request_with_creds,7,
>             [{file,"src/rabbitmq_aws.erl"},{line,404}]},
>         {rabbitmq_aws,handle_call,3,
>             [{file,"src/rabbitmq_aws.erl"},{line,164}]},
>         {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},
>         {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},
>         {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
> 
> =INFO REPORT==== 20-Nov-2016::22:53:51 ===
> Error description:
>    {could_not_start,rabbit,
>        {{function_clause,
>             [{rabbitmq_aws,format_response,
>                  [{error,
>                       {failed_connect,
>                           [{to_address,
>                                {"ec2.eu-central-1b.amazonaws.com",443}},
>                            {inet,[inet],nxdomain}]}}],
>                  [{file,"src/rabbitmq_aws.erl"},{line,229}]},
>              {rabbitmq_aws,perform_request_with_creds,7,
>                  [{file,"src/rabbitmq_aws.erl"},{line,404}]},
>              {rabbitmq_aws,handle_call,3,
>                  [{file,"src/rabbitmq_aws.erl"},{line,164}]},
>              {gen_server,try_handle_call,4,
>                  [{file,"gen_server.erl"},{line,615}]},
>              {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},
>              {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},
>         {gen_server,call,
>             [rabbitmq_aws,
>              {request,"ec2",get,[],
>                  "/?Action=DescribeInstances&Filter.1.Name=tag%3Aregion&Filter.1.Value.1=eu-central-1b&Filter.2.Name=tag%3Aservice&Filter.2.Value.1=rabbitmq&Version=2015-10-01",
>                  [],[],undefined}]}}}
