### ISSUE TITLE
cluster fails with consul

### ISSUE THREAD

**Issue by digitalkaoz** [aweber/rabbitmq-autocluster#66]
Hey, 

Consul registration seems fine with `0.6`  👍 

```
$ docker exec 2a9dcdbf4da1 sh -c "dig rabbitmq.service.consul"
;; QUESTION SECTION:
;rabbitmq.service.consul.   IN  A

;; ANSWER SECTION:
rabbitmq.service.consul. 0  IN  A   172.17.0.9
rabbitmq.service.consul. 0  IN  A   172.17.0.8
```

both nodes can tcp each other:

```
$ docker exec 2a9dcdbf4da1 telnet 172.17.0.9 5672
Trying 172.17.0.9...
Connected to 172.17.0.9.
Escape character is '^]'.
```

here my env vars (both nodes are 100% identical `docker-compose scale rabbitmq=2`

```
                "CONSUL_HOST=consul.service.consul",
                "CONSUL_ACL_TOKEN=",
                "RABBITMQ_ERLANG_COOKIE=secrect",
                "CONSUL_SVC_ADDR_NIC=eth0",
                "AUTOCLUSTER_TYPE=consul",
                "RABBITMQ_DEFAULT_PASS=guest",
                "RABBITMQ_DEFAULT_USER=guest",
                "CONSUL_PORT=8500",
                "RABBITMQ_LOGS=-",
                "RABBITMQ_SASL_LOGS=-",
                "RABBITMQ_VERSION=3.6.2",
                "RABBITMQ_DEBIAN_VERSION=3.6.2-1",
                "HOME=/var/lib/rabbitmq"
```

but still the cluster is not made up...the relevant log gave me this:

```
=INFO REPORT==== 4-Jun-2016::18:36:07 ===
autocluster: Delaying startup for 214ms.

=INFO REPORT==== 4-Jun-2016::18:36:07 ===
autocluster: Starting consul registration.

=INFO REPORT==== 4-Jun-2016::18:36:07 ===
autocluster: Registering node with consul.

=ERROR REPORT==== 4-Jun-2016::18:36:07 ===
** System NOT running to use fully qualified hostnames **
** Hostname 172.17.0.8 is illegal **

=ERROR REPORT==== 4-Jun-2016::18:36:07 ===
** System NOT running to use fully qualified hostnames **
** Hostname 172.17.0.9 is illegal **

=ERROR REPORT==== 4-Jun-2016::18:36:07 ===
autocluster: Can not communicate with cluster nodes.
```

setting a longname wont work in docker containers :/ 
and the node name is not! the ip, its:

```
=INFO REPORT==== 4-Jun-2016::18:47:58 ===
node           : rabbit@2a9dcdbf4da1
```

**Comment by digitalkaoz** [comment]
i guess its because the real node-name isnt stored in the consul service data and therefore i think you assume something wrong during clustering?!

**Comment by gmr** [comment]
Hmm no, it's more that erlang doesn't want to use the IP address for the node name  Check out https://www.rabbitmq.com/networking.html#dns

Do I understand what you want to do? On the same host/VM/etc:

- Use a single Consul server/agent running in a container
- Run two RabbitMQ containers that autocluster

If so, I'll work through the pattern and let you know what I come up with.

**Comment by digitalkaoz** [comment]
Thats exactly my (only my? I dont think so) use case. Throw some rabbitmq
nodes onto a docker swarm cluster and let them autocluster...on Production
each swarm peer has a consul, but all them in a consul cluster.

On Development i have 1 consul and x rabbitmq nodes...I think its not
different to a swarm cluster in the aspect of rabbitmq+consul clustering.

I would love to help on that issue, but im not into erlang. I can test and
Report Bugs :D

Gavin M. Roy <notifications@github.com> schrieb am Sa., 4. Juni 2016, 22:47:

**Comment by digitalkaoz** [comment]
"Every node in a cluster must be able to resolve every other node's
hostname, short or fully-qualified. By default RabbitMQ will use short
hostnames."

Mh thats a Problem...we cant use dockers deprecated "--link" function,
thats what a service discovery like consul is for...

Robert Schoenthal <seroscho@gmail.com> schrieb am Sa., 4. Juni 2016, 23:24:

**Comment by digitalkaoz** [comment]
Just for completeness i link the old issue here https://github.com/aweber/rabbitmq-autocluster/issues/60 so any reader gets why we need the ips for communication instand of ids here

**Comment by drpebcak** [comment]
I am hitting this same issue, except inside rancher instead of docker swarm. My rabbitmqs are registering in Consul with an IP, but the cluster is not forming.

**Comment by opHASnoNAME** [comment]
Same here with consul and 2 Docker - Hosts, is there any working example to get this running?

**Comment by binarin** [comment]
I have example working on top of k8s with etcd backend - https://github.com/binarin/rabbit-on-k8s-standalone
But I don't see why you can't make it work with consul and plain docker (except for #83)
Also there is a detailed explanation at this setup at https://www.mirantis.com/blog/clustered-rabbitmq-kubernetes/

**Comment by opHASnoNAME** [comment]
I have trouble to connect the nodes. We have two different Docker Hosts not using an Multi-Host Network, so i would love to use the "Host-ips" to connect the cluster. This only works when i add each host to the hosts file on the container.. but thats not a "automatic" solution.. further i am unsure why i need Consul for such a setup?



`docker run --privileged -h 192.168.99.100 \
  -e AUTOCLUSTER_TYPE=consul \
  -e AUTOCLUSTER_DELAY=50 \
  -e CONSUL_HOST=192.168.99.100 \
  -e CONSUL_SVC_ADDR=192.168.99.100 \
  -e RABBITMQ_NODENAME=rabbit1 \
  -e AUTOCLUSTER_CLEANUP=true \
  -e RABBITMQ_USE_LONGNAME=true \
  -p 4369:4369 \
  -p 5672:5672 \
  -p 15672:15672 \
  -p 25672:25672 \
  gavinmroy/alpine-rabbitmq-autocluster`

and on the other node:

`
  docker run --privileged -h 192.168.99.101 \
    -e AUTOCLUSTER_TYPE=consul \
    -e AUTOCLUSTER_DELAY=50 \
    -e CONSUL_HOST=192.168.99.101 \
    -e CONSUL_SVC_ADDR=192.168.99.101 \
    -e RABBITMQ_NODENAME=rabbit2 \
    -e AUTOCLUSTER_CLEANUP=true \
    -e RABBITMQ_USE_LONGNAME=true \
    -p 4369:4369 \
    -p 5672:5672 \
    -p 15672:15672 \
    -p 25672:25672 \
    gavinmroy/alpine-rabbitmq-autocluster`

both running consul and registering correct with:

service:rabbitmq:192.168.99.100 / service:rabbitmq:192.168.99.101

if you have any tipps.. this would made my day ;)

**Comment by binarin** [comment]
`RABBITMQ_NODENAME=rabbit2` - this doesn't look correct. Correct version should be `rabbit@192.168.99.100` etc. And this is also mentioned in a blog post that I've referenced.

**Comment by opHASnoNAME** [comment]
Thanks for your support, i have trouble with:

> Even before trying to start any rabbits, you need to be sure that containers can reach each other using selected naming scheme – for example, a ping should work with the part that comes after the @

I thought consul would handle this, if i have to ping the other container on a different docker host i need DNS or modified hosts eh?

**Comment by binarin** [comment]
No, autocluster/consul is used ONLY as a discovery mechanism. It just stores the hostname part of every `RABBITMQ_NODENAME`  - so any starting node can fetch this hostname and reconstruct remote RABBITMQ_NODENAME. Everything else happens using the regular erlang distribution mechanism - so this name needs to be resolvable (unless the IP address is used), and at least ports 4369 and 25672 should be available there for every other machine in the cluster.

**Comment by binarin** [comment]
You already have almost everything needed in place for successful clustering - by exposing ports 4369 and 25672 on the host. From the erlang distribution standpoint that makes a host equivalent to the rabbitmq container running there (with the only downside that you can run only one such container per host). So for a hostname part of RABBITMQ_NODENAME you can use either host IP or host DNS (if any).

**Comment by opHASnoNAME** [comment]
Thanks a lot for clarification.. maybe i am just to stupid .. or it is not possible (consul registers fine)

<img width="796" alt="bildschirmfoto 2017-01-13 um 13 57 06" src="https://cloud.githubusercontent.com/assets/5878780/21930793/34c04840-d998-11e6-8b03-4af33744784a.png">


```
docker run --privileged -h 192.168.99.100 --net=host \
  -e AUTOCLUSTER_TYPE=consul \
  -e AUTOCLUSTER_DELAY=50 \
  -e CONSUL_HOST=192.168.99.100 \
  -e RABBITMQ_NODENAME=rabbit1@192.168.99.100 \
  -e AUTOCLUSTER_CLEANUP=true \
  -e RABBITMQ_USE_LONGNAME=true \
  -p 4369:4369 \
  -p 5672:5672 \
  -p 15672:15672 \
  -p 25672:25672 \
  rabbit-cluster

docker run --privileged --net=host -h 192.168.99.101 \
  -e AUTOCLUSTER_TYPE=consul \
  -e AUTOCLUSTER_DELAY=50 \
  -e CONSUL_HOST=192.168.99.101 \
  -e RABBITMQ_NODENAME=rabbit2@192.168.99.101 \
  -e AUTOCLUSTER_CLEANUP=true \
  -e RABBITMQ_USE_LONGNAME=true \
  -p 4369:4369 \
  -p 5672:5672 \
  -p 15672:15672 \
  -p 25672:25672 \
  rabbit-cluster
```

**Comment by opHASnoNAME** [comment]
This setup is working, but seems to be a bit unflexible with add-hosts:

```
    docker run --rm --privileged --net=host --add-host="rabbit2:192.168.99.101" \
      -e AUTOCLUSTER_TYPE=consul \
      -e RABBITMQ_USE_LONGNAME=false \
      -e CONSUL_SVC_ADDR=rabbit1 \
      -e CONSUL_HOST=192.168.99.100 \
      -p 4369:4369 \
      -p 5672:5672 \
      -p 15672:15672 \
      -p 25672:25672 \
      gavinmroy/alpine-rabbitmq-autocluster

    docker run --rm --privileged --net=host --add-host="rabbit1:192.168.99.100" \
      -e AUTOCLUSTER_TYPE=consul \
      -e RABBITMQ_USE_LONGNAME=false \
      -e CONSUL_SVC_ADDR=rabbit2 \
      -e CONSUL_HOST=192.168.99.101 \
      -p 4369:4369 \
      -p 5672:5672 \
      -p 15672:15672 \
      -p 25672:25672 \
      gavinmroy/alpine-rabbitmq-autocluster
```

**Comment by opHASnoNAME** [comment]
Sometimes.. this should be the Race condition mentioned in the blog posting (with consul)

**Comment by Gsantomaggio** [comment]
@digitalkaoz 

We got the problem:
```
consul1    |     2017/03/20 16:05:45 [DEBUG] agent: Node info in sync
rabbit_2   |
rabbit_2   | =ERROR REPORT==== 20-Mar-2017::16:05:45 ===
rabbit_2   | ** System NOT running to use fully qualified hostnames **
rabbit_2   | ** Hostname 172.29.0.3 is illegal **
rabbit_2   |
rabbit_2   | =ERROR REPORT==== 20-Mar-2017::16:05:45 ===
rabbit_2   | autocluster: Can not communicate with cluster nodes.
```

The problem is that you are using `CONSUL_SVC_ADDR_NIC=eth0` and the plugin registers the node on consul as:
`service:rabbitmq:172.29.0.3`   ( because it uses [ inet:getifaddrs()](https://github.com/rabbitmq/rabbitmq-autocluster/blob/rabbitmq-autocluster-62/src/autocluster_util.erl#L122) )

when the plugin tries to join the nodes you got the error `Hostname 172.29.0.3 is illegal` 

This is more and Erlang problem than an RabbitMQ problem, for example:

node1:
```
➜  ~ erl -name node1@this.node.consul
Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.1  (abort with ^G)
(node1@this.node.consul)1>
```

node2:
````
➜  ~ erl -sname node2
Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.1  (abort with ^G)
(node2@mac)1> net_kernel:connect('node1@this.node.consul').
false

=ERROR REPORT==== 20-Mar-2017::17:43:01 ===
** System NOT running to use fully qualified hostnames **
** Hostname this.node.consul is illegal **
(node@mac)2>
````

So you should not use "eth0" or try to use long name. 
[Here is an working example using consul](https://github.com/Gsantomaggio/rabbitmqexample/tree/master/cluster_docker_compose/consul_ha)
