### ISSUE TITLE
AWS backend requires host mapping for "instance-data"

### ISSUE THREAD

**Issue by ml019** [aweber/rabbitmq-autocluster#67]
The AWS backend currently uses "instance-data" as the host name when fetching the instance id. I had to add a host entry mapping this to 169.254.169.254.

Should code use the IP address rather than the name? Alternatively, did I miss it somewhere in the documentation where this is described?

Thanks

**Comment by gmr** [comment]
Hmm no -- while I've not had an issue with that, perhaps that's distro specific or something. I'll move it to the IP address.

OOC what OS/ver are you using where that's not resolving?

**Comment by gmr** [comment]
I thought of a scenario where this can occur -- not using the AWS DNS servers, which is probably the case with something like kubernetes or other dockerized solutions.

**Comment by gmr** [comment]
``0.6.1`` was just released. Thanks for reporting this!

**Comment by ml019** [comment]
Thanks for fixing it. 

I am using the AWS custom AMI for ECS within a VPC with enableDnsSupport set to true.

It appears the official way to get the metadata is to use the IP address - https://forums.aws.amazon.com/message.jspa?messageID=536813.

However, it also seems that there is an undocumented feature whereby "instance-data" is defined in the private DNS AWS provides _**if**_ enableDnsHostnames is enabled (at least that's what my testing suggests). 

Originally I had this setting disabled which is when I got the problem with the AWS backend not resolving "instance-data". 

However, in order to get autocluster to work, I needed the rabbit node names to resolve via DNS (and match those returned via the ASG query). The simplest way to achieve this was to align the rabbit node name to the private DNS name AWS provided for the docker instance. To do this I enabled dns hostnames, and then found instance-data was now resolving.

So I have used your docker image as a base and wrapped a startup script to get the private dns entry for the host and use it to define RABBITMQ_NODENAME. It means I can only have one rabbit container per docker instance, but that is all I need at present. 

Given the dependency on the AWS ASG query, I can't see how you can make ASG based clustering work without aligning the node name to the AWS private dns entry for the docker instance. Have you got it working without this step? I am relatively new to rabbit so please forgive me if its blindingly obvious how to resolve the question of node names without aligning to the docker instance host name.

Thanks for making your work public.

Regards
Michael

**Comment by gmr** [comment]
You are correct, there is no way to resolve node names without aligning to docker instance host name. Is a base expectation of how the clustering works that the locally resolvable name of the node is what's used to connect to the node.
