### ISSUE TITLE
error thrown on startup: bad term

### ISSUE THREAD

**Issue by j-fernandes** [aweber/rabbitmq-autocluster#68]
Hello, 

Im not sure what Im not doing correctly. Im trying to get this going in an autoscaling group in AWS, and have done the following:

- launched an Ubuntu 16.04 AMI and installed rabbitmq, added some custom config (queues, exchanges,  etc), the management plugin and a few others, and the autocluster 0.60 pieces into the plugins directory and enabled it (no config in there for the autocluster plugin). Started and seems to be doing its thing, so made an AMI of it,
- Put the AMI into a launch config, and autoscaling group and launched a single instance and then attempted to add the autocluster plugin config to it - plan is to get it going on the one instance and then i'll make a fresh ami and update the lauch config and ASG. However whenever the autocluster config to it and I attempt to start rabbit I get the following error: 

`Crash dump was written to: erl_crash.dump
could not start kernel pid (application_controller) (error in config file "/etc/rabbitmq/rabbitmq.config" (1): bad term)
`
and my config is : 
```erlang
[
  {rabbit,
    [
      {log_levels, [{autocluster, debug}, {connection, info}]},
      { tcp_listeners, [ 5672 ] },
      { ssl_listeners, [ ] },
      {loopback_users, []}
    ]
  },
  { rabbitmq_management, [
      {load_definitions, "/etc/rabbitmq/custom_definitions.json"},
      { listener, [
        { port, 15672 },
        { ssl, false }
        ]
      }
    ]
  },
  {autocluster, [
    {backend, aws},
    {aws_autoscaling, true},
    {aws_ec2_region: "ap-southeast-2"}
  ]}
].
```

Cannot quite figure out what is incorrect here, would appreciate if someone could point out what Im doing incorrectly?

Thanks

**Comment by gmr** [comment]
There was a typo in my example that you copied.  Change `` {aws_ec2_region: "ap-southeast-2"}`` to `` {aws_ec2_region, "ap-southeast-2"}``

**Comment by j-fernandes** [comment]
Thanks @gmr, thats got it starting up now :)

So now I have two nodes based on this ami with an elb in front of them and can access the management interface on both. All ports open so the two can communicate but cant seem to verify that the cluster has 2 nodes. Testing a few messages seems to get them in one or the other, but messages arent being replicated across the cluster.

How does one test that autocluster is working properly? The logs dont have any info apart from garbage collection stats. And running `rabbitmqctl cluster_status` only shows the individual node - doesnt seem to have put the second node in the cluster.

**Comment by gmr** [comment]
Do you mind trying the CloudFormation template [here](https://github.com/gmr/alpine-rabbitmq-autocluster) and comparing what it sets up with what you've done? It's non-intrusive, as you can delete the cloud formation stack after you're done and all traces will be removed.

**Comment by gmr** [comment]
Closing for lack of response.
