### ISSUE TITLE
when Consul ACL will be supported?

### ISSUE THREAD

**Issue by scopenco** [aweber/rabbitmq-autocluster#69]
Hello,

i sent PR last time that fix Consul ACL support to plugin ver 0.5. (https://github.com/aweber/rabbitmq-autocluster/pull/58) and you merged it to master.
Now i don't see any settings in Wiki that allow to set ACL in plugin ver 0.6.0.

When this support will be enabled?

**Comment by scopenco** [comment]
I've found undocumented option in source code 'consul_acl_token'. Please describe it in wiki.

**Comment by michaelklishin** [comment]
According to GitHub [your commit](https://github.com/aweber/rabbitmq-autocluster/commit/15fdfe3c1d55a0af9c693b7d15a68f5cda8d2487) is included into 0.6.0. Have you tried it?

Can you please clarify what your concern is, that the wiki is out of date, your commit didn't make it into the release or is it something else?

**Comment by scopenco** [comment]
I dont see any reference about option 'consul_acl_token' in wiki.

**Comment by michaelklishin** [comment]
I'm not a repo collaborator and [can edit the Consul wiki page](https://github.com/aweber/rabbitmq-autocluster/wiki/Consul-Configuration/_edit). Have you considered adding it?

**Comment by gmr** [comment]
It's in the wiki, I'm not sure what you're missing. Look for "Consul ACL Token" on this page:

https://github.com/aweber/rabbitmq-autocluster/wiki/Consul%20Configuration
