### ISSUE TITLE
Split-brain can go completely unnoticed

### ISSUE THREAD

**Issue by binarin** [aweber/rabbitmq-autocluster#73]
After executing the following scenario:
- 3 nodes form a cluster
- network partition splits those nodes from rest of the network (including etcd server)
- etcd discards nodes info due to TTL
- 3 more nodes form a new cluster
- network partition heals

We will have 2 completely independent clusters, with 3 nodes in
   each. And there is no functionality either in rabbitmq or in
   autocluster plugin that will allow to detect and heal such situation.

So I'm thinking about extending `autocluster_cleanup` in following way:
- Regularly check that we are clustered with the first alive node returned by backend
- If more than configured amount of such health-checks fails, and
   `autocluster_failure` is set to `stop`, we stop current node.

This way we would have all rabbit-specific error handling inside
   rabbit itself, and any external tools we are using for managing
   rabbit (systemd, supervisord, mesos, ...) should be responsible
   only for restarting failed nodes.

WDYT?

**Comment by gmr** [comment]
I don't know if cleanup is the right spot for that. I'm wondering if there should be a separate proc/configuration for that. Let me chew on the use case and get back to you. I'm going to be on vacation for the next week, so if I don't get back to you before next week, please don't take it personally.

**Comment by binarin** [comment]
It's even worse than that. Frequently 3-node cluster assembly (from a scratch) results in a split-brain (i.e. when things settle down, we have 1-node cluster and 2-nodes cluster). I think with current rabbit architecture the best thing that can be done is to use logic similar to https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-server-ha.ocf
