### ISSUE TITLE
no_configured_tags when attempting to use EC2 Tags

### ISSUE THREAD

**Issue by kevinmannn** [aweber/rabbitmq-autocluster#75]
When I try to setup auto-clustering using EC2 tags, I get the following error every time in my log.

=INFO REPORT==== 5-Jul-2016::01:03:29 ===
autocluster: Delaying startup for 2825ms.

=INFO REPORT==== 5-Jul-2016::01:03:31 ===
autocluster: Starting aws registration.

=ERROR REPORT==== 5-Jul-2016::01:03:31 ===
autocluster: Could not fetch node list from autocluster_aws: no_configured_tags.

I have looked around the source code of the plugin, and I see that this shows up when get_tags() is undefined or [] and passed into get_node_list_from_tags (https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_aws.erl#L141).  My Erlang knowledge is minimal, but on line 182 of the same file, does get_tags() only ever return []? I also don't see anywhere that aws_ec2_tags configuration setting is used.

I have the following configuration:
rabbitmq.conf:
```
  {autocluster, [
    {backend, aws},
    {aws_ec2_tags, [{"role", "rabbitmqnode"}, {"Service", "rabbitmq"}]},
    {aws_ec2_region, "us-west-2"}
  ]}
```
I have set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables.  

Any help on this would be greatly appreciated.

**Comment by gmr** [comment]
My off-the-cuff guess is your IAM user with the access key/secret key doesn't have access to the proper EC2 API calls.

Are you sure your policy is setup and attached to the user?

https://github.com/aweber/rabbitmq-autocluster/wiki/AWS%20Configuration#iam-policy

**Comment by kevinmannn** [comment]
Thanks for the quick response. 

I verified my IAM user and I have both the autoscaling:DescribeAutoScalingInstances and ec2:DescribeInstances permissions. 

Not sure if it makes a difference, but I have also set RABBITMQ_USE_LONGNAME as an environment variable.

**Comment by gmr** [comment]
Bah, I see that somehow the ``get_tags/0`` function is unimplemented which I seem to remember wasn't the case and I missed in the final QA check. I'll go back and see what's up there. I'm heading out for a week long vacation tomorrow, but will see what I can dig up in my local repo ASAP. Stay tuned.

**Comment by kevinmannn** [comment]
It's good to hear that it's not just me lol.  Thanks for looking into this!

**Comment by slem44** [comment]
Is there a work around for this problem?

I am getting the same error.

Stan

**Comment by wyardley** [comment]
I have this problem as well. Is there any supported way to get this to work as documented without using autoscaling?

Would also be great to be able to filter by security-group.
