### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by shamil** [aweber/rabbitmq-autocluster#78]
Thanks for the plugin
Is it possible to push a new release with the fixes by @binarin?

**Comment by gmr** [comment]
He's a machine and I don't think he's quite done with his PRs yet. I'm going to be fixing the AWS tag support before the next release.

**Comment by shamil** [comment]
I'm particularity interested in #72 which is a deal breaker for me, but you're right, let's wait for @binarin finish his sprint...

**Comment by shamil** [comment]
@gmr will there be release cut any time soon?
thanks

**Comment by f1yers** [comment]
@gmr We'd love to use this plugin and leverage the ec2 tags but sadly we're not able to atm due to #75.  Since the fix was merged, any chance on getting a release out soon?

**Comment by rhoegg** [comment]
I made an [interim release](https://github.com/rhoegg/rabbitmq-autocluster/blob/master/autocluster-0.6.2-rhoegg.ez) from a fork of master from today that seems to work for me.

**Comment by forstermatth** [comment]
@rhoegg I tried to use your interim release, but as soon as I added it to my image, I lost SSH capabilities into the box. Not sure if it is related, but it's the only change I made from one version to the next.

**Comment by shamil** [comment]
a friendly reminder. there was no new release since June last year.
should we expect for new one anytime soon?

**Comment by Gsantomaggio** [comment]
@shamil [here](https://github.com/rabbitmq/rabbitmq-autocluster/releases/tag/0.7.0-rc1) you can find the version (`0.7.0-rc1`) released by the RabbitMQ team

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
