### ISSUE TITLE
Cluster using Auto Scaling Groups. Terminated instances still showing on cluster?

### ISSUE THREAD

**Issue by ricardclau** [aweber/rabbitmq-autocluster#81]
Hi

We are testing the autocluster using Auto Scaling Groups and we have discovered that when you "recycle" the members of the cluster (terminate one instance, ASG triggers a new one, new one joins the cluster) the terminated instance stays there

Is this a bug? An expected behaviour? Any way to automate this removing?

**Comment by binarin** [comment]
Hi.
Did you set all those options?

                                      ,{cleanup_interval, 10}
                                      ,{cluster_cleanup, true}
                                      ,{cleanup_warn_only, false}

**Comment by ricardclau** [comment]
Oh, did not know about them, really new to this plugin! 

Could not find them documented at https://github.com/aweber/rabbitmq-autocluster/wiki/AWS%20Configuration but now I see them at https://github.com/aweber/rabbitmq-autocluster/wiki/General-Settings

Sorry and thanks for answering!
