### ISSUE TITLE
Startup races

### ISSUE THREAD

**Issue by binarin** [aweber/rabbitmq-autocluster#83]
Randomized startup delay is a poor protection against assembling clusters that are in split-brain situation right from the start. It's actually different from #73 

Some sort of explicit lock during boot is required.

I think I'm ready to tackle this problem for etcd backend. 

Will it be OK if I extend `autocluster_backend` with `lock`/`unlock` callbacks and add calls to them into `autocluster.erl`?

**Comment by gmr** [comment]
Sure, though it'd need to be implemented in a way that the random delay still works for things that can't implement lock/unlock. What were you thinking there?

**Comment by binarin** [comment]
I don't know yet. Maybe just some note on wiki that for backends with locking support, delay can be set to 0.

**Comment by binarin** [comment]
@gmr Is there a reason why `consul` backend is the only one that implements `register` callback and that this registration happens very early during startup? I'm thinking about following things:
- Moving `Backend:register/0` at the point where node was already clustered
- Add proper implementation `register/0` in every backend, where it e.g. can start TTL updater without all this `rabbit_boot_step` magic

Then whole startup sequence can be reformulated as following sequence of steps without any implicit magic:
1) Validate backend options
2) Acquire backend lock
3) Fetch nodelist from backend and choose best node to join to
4) Maybe perform clustering
5) Register node in backend
6) Release backend lock

But it'll result in a significant revamp of `autocluster.erl`. WDYT?

**Comment by binarin** [comment]
Here is relevant part  from my work-in-progress https://github.com/binarin/rabbitmq-autocluster/blob/startup-locking-support/src/autocluster.erl#L22-L184

While it's pretty big change from what was there before, I think that it's still worth it:
- Reduced number of steps from 13 to 6
- Those steps are now independent, i.e. they can be more thoroughly tested (and more easier than in `autocluster_boot_tests.erl`)

@gmr So if you are OK with overall shape of this, I'll continue making it work and polishing.
