### ISSUE TITLE
Problems with error handling in dns clustering and some documentation to be added?

### ISSUE THREAD

**Issue by ricardclau** [aweber/rabbitmq-autocluster#84]
Hi

I was having issues setting up a cluster using the DNS backend and I decided to look at the code in https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_dns.erl#L48:L65

Sorry in advance if I am asking something a bit stupid as my Erlang knowledge is VERY small :)

So, if we run the gethostbyaddr function with non existing entries (suppose this ip address is not in the reverse lookup zone in the dns server)
1> inet_res:gethostbyaddr("10.10.2.248").
{error,nxdomain}
Or if the format is wrong
2> inet_res:gethostbyaddr("meh").
{error,formerr}

However, the pattern matching at https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_dns.erl#L63 is expecting an Error variable instead of these 2 vars

I could not find the error in the logs and it was driving me crazy... can this be a bug in the error handling? Or is this me not understanding how Erlang works :)

Then I also found another thing related to this code. The cluster could not be formed until I created some reverse lookup entries for each host. So, creating the round robin A record was not enough but also the reverse DNS entries per each host are needed.

Maybe this is obvious but it made me scratch my head for a while. Happy to send PRs.

Thanks anyway for this excellent plugin, it works like a charm when everything is in place!

**Comment by gmr** [comment]
If you have time, updating the DNS wiki page would be helpful for others going down this road. It should be open for updating...

**Comment by ricardclau** [comment]
Hi @gmr 

Just added some config example and all the troubleshooting I did at https://github.com/aweber/rabbitmq-autocluster/wiki/DNS-Configuration

Please let me know your thoughts on it!

**Comment by gmr** [comment]
Looks great, thanks!
