### ISSUE TITLE
Federation support

### ISSUE THREAD

**Issue by kristianpaul** [aweber/rabbitmq-autocluster#86]
When you do discovery by DNS from multiple regions you'll need to implement federation for a reliable cluster setup

**Comment by michaelklishin** [comment]
Federation is not a replacement for clustering. What specifically are you requesting from this plugin?

**Comment by kristianpaul** [comment]
Isnt federation required if you want to cluster different rmq instances that are prone to network partitions?

**Comment by michaelklishin** [comment]
@kristianpaul it is recommended for WAN links but still not a replacement for clustering. Please first investigate how things work before you jump in to file issues and make bold claims. This plugin does not intend to cover cross-WAN installations.

**Comment by michaelklishin** [comment]
@gmr I believe this should be closed: it's too vague and non-actionable, and probably out of scope for this plugin anyway.
