### ISSUE TITLE
Proxy server support

### ISSUE THREAD

**Issue by reid-harrison** [aweber/rabbitmq-autocluster#87]
My AWS private cloud can only be reached through a proxy server but rabbitmq-autocluster does not support proxy server configuration. Because of this, I am unable to use the plugin.

**Comment by nickclare** [comment]
Hi, I'm also facing this issue. Is there any workaround?

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
