### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Stono** [aweber/rabbitmq-autocluster#91]
Hey guys
Started getting this today when doing a `make dist`, not sure why, any ideas?

```
15:12:12.286 HEAD is now at a8271e8... Merge pull request #89 from xek/k8s-plugin
15:12:12.346  DEP    rabbit_common
15:12:22.713 error: rabbitmq-components.mk must be updated!
```

**Comment by michaelklishin** [comment]
`rabbitmq-components.mk` in this repository needs syncing with `rabbitmq/rabbitmq-common`.

**Comment by Stono** [comment]
OK, I build a specific version of that from source too so guess I can find
it in that tar somewhere. Ta.

**Comment by michaelklishin** [comment]
@Stono can you please close this issue then?

**Comment by Stono** [comment]
Had much messing about getting this working, syncing from master didn't work as I'm building a specific version of the server, with a patch.    Ended up get mysterious 500 errors when creating queues.

Got there in the end though.
https://github.com/peopledata/td.rabbitmq

Ta
