### ISSUE TITLE
Cluster name configurable

### ISSUE THREAD

**Issue by blakebarnett** [aweber/rabbitmq-autocluster#97]
It would be nice if the cluster name were configurable and present in the Consul service record as a tag (or just kv store to make it more generic across backends) so that it could be used to automatically determine what cluster to connect to in the case of concurrently running clusters.

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster
