### ISSUE TITLE
rabbitmq-aws plugin doing unnecessaary calls to AWS API on rabbitmq start

### ISSUE THREAD

**Issue by ss7pro** [aweber/rabbitmq-autocluster#99]
Hey,

FIs there anyway we can stop rabbitmq-aws plugin doing calls to AWS api ? On my setup it eats about 2 minutes (due to multiple circumstances :P)

=ERROR REPORT==== 10-Oct-2016::15:30:38 ===
Failed to retrieve AWS credentials: undefined

It would be nice that we somehow stop this plugin from doing it's work when aws integration is not used.

**Comment by gmr** [comment]
To be specific, are the calls you're referring to the ones that are trying to query the local instance metadata server for credentials when none are provided?

**Comment by ss7pro** [comment]
I'm using latest version, but this message comes from rabbitmq-aws plugin not autocluster.

**Comment by ss7pro** [comment]
Hey,

I fiugured out that. rabbitmq-aws plugin is always trying to reach metadata server, to get credentials data. I've opened a bug in their repo: https://github.com/gmr/rabbitmq-aws/issues/2
